# Generated by Django 5.2.16 on 2026-08-19 09:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0021_add_committee_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsProduct',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.SlugField(help_text='Short unique code, e.g. regular, td-12, share.', max_length=40, unique=True)),
                ('product_type', models.CharField(choices=[('share_capital', 'Share capital'), ('regular', 'Regular savings'), ('time_deposit', 'Time deposit'), ('special', 'Special savings'), ('capital_build_up', 'Capital build-up (CBU)')], default='regular', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('interest_rate', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Annual interest rate in percent (e.g. 3.500 = 3.5%).', max_digits=6)),
                ('compounding', models.CharField(choices=[('none', 'No compounding (simple)'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='annually', max_length=16)),
                ('min_opening_deposit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum amount required to open an account.', max_digits=12)),
                ('min_maintaining_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance that must remain after a withdrawal.', max_digits=12)),
                ('min_additional_deposit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum amount for later deposits. 0 means any amount is allowed.', max_digits=12)),
                ('term_months', models.PositiveIntegerField(default=0, help_text='Fixed term in months for time deposits. 0 = open-ended (no maturity).')),
                ('allows_withdrawal', models.BooleanField(default=True, help_text='Uncheck for products that cannot be withdrawn (e.g. share capital).')),
                ('withdrawal_notice_days', models.PositiveIntegerField(default=0, help_text='Days of notice required before a withdrawal. 0 = same day.')),
                ('max_free_withdrawals_per_month', models.PositiveIntegerField(default=0, help_text='Free withdrawals allowed per calendar month. 0 = unlimited.')),
                ('early_withdrawal_penalty_percent', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Penalty % of withdrawn amount if taken before maturity.', max_digits=6)),
                ('dividend_eligible', models.BooleanField(default=False, help_text='Counts toward patronage / dividend computation (typical for share capital).')),
                ('required_for_membership', models.BooleanField(default=False, help_text='Members are expected to hold this product (e.g. share capital).')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Savings product',
                'verbose_name_plural': 'Savings products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MemberSavingsAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(editable=False, max_length=32, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('active', 'Active'), ('dormant', 'Dormant'), ('matured', 'Matured'), ('closed', 'Closed')], db_index=True, default='active', max_length=16)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('maturity_date', models.DateField(blank=True, help_text='Set automatically from the product term when the account is opened.', null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_accounts', to='members.member')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='savings.savingsproduct')),
            ],
            options={
                'verbose_name': 'Member savings account',
                'verbose_name_plural': 'Member savings accounts',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='SavingsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('opening', 'Opening deposit'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('interest', 'Interest credit'), ('penalty', 'Penalty'), ('adjustment', 'Adjustment')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(editable=False, max_length=32, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='savings.membersavingsaccount')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Savings transaction',
                'verbose_name_plural': 'Savings transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
