# Generated by Django 5.2.16 on 2026-08-25 10:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsproduct',
            name='max_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000000.00'), help_text='Maximum account balance. 0 = no limit.', max_digits=14),
        ),
    ]
