# Generated by Django 5.2.16 on 2026-08-26 03:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_savingsproduct_max_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersavingsaccount',
            name='opened_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="Official date and time this member's savings account was opened."),
        ),
    ]
