# Generated by Django 5.2.16 on 2026-08-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_member_status_model'),
        ('savings', '0003_membersavingsaccount_opened_at_help_text'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='membersavingsaccount',
            index=models.Index(fields=['status', '-opened_at'], name='savings_acct_status_opened'),
        ),
    ]
