# Generated by Django 5.2.8 on 2025-12-17 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0005_deletedmember"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundTransferOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient_rfid", models.CharField(max_length=50)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("notes", models.TextField(blank=True)),
                ("otp_code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_otps",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fund Transfer OTP",
                "verbose_name_plural": "Fund Transfer OTPs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["member", "otp_code", "is_used"],
                        name="mobile_api__member__876df5_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="mobile_api__expires_4a440b_idx"
                    ),
                ],
            },
        ),
    ]
