# Generated by Django 5.2.8 on 2026-04-19 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0009_remove_member_app_password_hash"),
        ("mobile_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BiometricEnrollOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp_code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biometric_otps",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Biometric Enroll OTP",
                "verbose_name_plural": "Biometric Enroll OTPs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["member", "otp_code", "is_used"],
                        name="mobile_api__member__bff872_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="mobile_api__expires_622226_idx"
                    ),
                ],
            },
        ),
    ]
