# Generated by Django 5.2.8 on 2026-04-19 12:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0009_remove_member_app_password_hash"),
        ("mobile_api", "0002_biometricenrollotp"),
    ]

    operations = [
        migrations.CreateModel(
            name="QRFeatureSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Globally enable or disable QR code fund transfers.",
                        verbose_name="Enable QR Transfer Feature",
                    ),
                ),
                (
                    "max_transfer_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=50000.0,
                        help_text="Maximum single transfer allowed when using a QR code scan. 0 = no limit.",
                        max_digits=10,
                        verbose_name="Max Transfer Amount via QR (₱)",
                    ),
                ),
                (
                    "qr_token_regenerate_on_use",
                    models.BooleanField(
                        default=False,
                        help_text="If enabled, each member's QR token changes after a successful QR transfer.",
                        verbose_name="Regenerate QR Token After Each Transfer",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "QR Feature Settings",
                "verbose_name_plural": "QR Feature Settings",
            },
        ),
        migrations.CreateModel(
            name="MemberQRCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qr_token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique token embedded in the member's QR code.",
                        unique=True,
                        verbose_name="QR Token",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Disable to temporarily block QR transfers for this member.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "scan_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Total Scans"
                    ),
                ),
                (
                    "last_scanned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Scanned"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_code",
                        to="members.member",
                        verbose_name="Member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member QR Code",
                "verbose_name_plural": "Member QR Codes",
                "ordering": ["member__first_name", "member__last_name"],
            },
        ),
    ]
