# Generated by Django 5.2.8 on 2025-12-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SentDailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(help_text="Date of the report")),
                (
                    "recipient_email",
                    models.EmailField(
                        help_text="Email address that received the report",
                        max_length=254,
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the report was sent"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sent Daily Report",
                "verbose_name_plural": "Sent Daily Reports",
                "ordering": ["-report_date", "-sent_at"],
                "unique_together": {("report_date", "recipient_email")},
            },
        ),
    ]
