# Generated by Django 5.2.8 on 2025-12-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for the email credential (e.g., 'Genglo Printing Services')",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address used for sending (hidden in email headers for security)",
                        max_length=254,
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        help_text="Email password or app password", max_length=255
                    ),
                ),
                (
                    "smtp_host",
                    models.CharField(
                        default="smtp.gmail.com",
                        help_text="SMTP server hostname",
                        max_length=255,
                    ),
                ),
                (
                    "smtp_port",
                    models.IntegerField(default=587, help_text="SMTP server port"),
                ),
                (
                    "use_tls",
                    models.BooleanField(default=True, help_text="Use TLS encryption"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this credential is currently active",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Use this credential as the default sender",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Email Credential",
                "verbose_name_plural": "Email Credentials",
                "ordering": ["-is_default", "name"],
            },
        ),
    ]
