# Generated by Django 5.2.8 on 2026-01-26 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0002_emailcredential"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailCredential",
        ),
    ]
