# Generated by Django 5.2.8 on 2026-02-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0003_delete_emailcredential"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrinterSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "printer_name",
                    models.CharField(
                        default="XP-58",
                        help_text="Exact name of the printer as it appears in Windows (e.g. XP-58, EPSON TM-T88V).",
                        max_length=100,
                    ),
                ),
                (
                    "paper_size",
                    models.CharField(
                        choices=[
                            ("58mm", "58 mm (narrow roll)"),
                            ("80mm", "80 mm (standard roll)"),
                            ("A4", "A4 (full page)"),
                        ],
                        default="58mm",
                        help_text="Paper roll width loaded in the printer.",
                        max_length=10,
                    ),
                ),
                (
                    "auto_print_on_load",
                    models.BooleanField(
                        default=True,
                        help_text="When enabled, the receipt page opens the print dialog automatically so the cashier does not need to click the Print button.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Printer Settings",
                "verbose_name_plural": "Printer Settings",
            },
        ),
    ]
