# Generated by Django 5.2.8 on 2026-04-16 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0004_printersettings"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PrinterSettings",
        ),
    ]
