# Generated by Django 5.2.8 on 2026-04-19 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0005_delete_printersettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportScheduleConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hour",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Hour to send the report (0–23, 24-hour format).",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ],
                    ),
                ),
                (
                    "minute",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Minute to send the report (0–59).",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(59),
                        ],
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to pause automatic report sending.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Report Schedule Config",
                "verbose_name_plural": "Report Schedule Config",
            },
        ),
    ]
