# Generated by Django 5.2.8 on 2026-04-19 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0006_reportscheduleconfig"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportscheduleconfig",
            name="hour",
        ),
        migrations.RemoveField(
            model_name="reportscheduleconfig",
            name="minute",
        ),
        migrations.AddField(
            model_name="reportscheduleconfig",
            name="send_time",
            field=models.TimeField(
                default=datetime.time(0, 0),
                help_text="Time to send the daily report (e.g. 12:00 AM = 00:00, 8:00 PM = 20:00).",
            ),
        ),
    ]
