# Generated by Django 5.2.8 on 2026-04-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0007_use_timefield_for_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "store_name",
                    models.CharField(
                        default="Genglo Printing Services",
                        help_text="Official store / business name.",
                        max_length=120,
                    ),
                ),
                (
                    "branch_name",
                    models.CharField(
                        blank=True,
                        help_text="Branch label, e.g. 'Main Branch' or 'SM Pampanga Branch'.",
                        max_length=120,
                    ),
                ),
                (
                    "address_line1",
                    models.CharField(
                        blank=True,
                        help_text="Street / building address.",
                        max_length=200,
                    ),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True,
                        help_text="Barangay, subdivision, or unit number (optional).",
                        max_length=200,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, help_text="City or municipality.", max_length=100
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, help_text="Province or region.", max_length=100
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True, help_text="Postal / ZIP code.", max_length=20
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(
                        blank=True,
                        help_text="Primary contact number (e.g. 0917-123-4567).",
                        max_length=30,
                    ),
                ),
                (
                    "alt_contact_number",
                    models.CharField(
                        blank=True,
                        help_text="Alternative / landline number (optional).",
                        max_length=30,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Store email address (optional).",
                        max_length=254,
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, help_text="Store website URL (optional)."
                    ),
                ),
                (
                    "business_hours",
                    models.CharField(
                        blank=True,
                        help_text="Operating hours, e.g. 'Mon–Sat 8 AM – 6 PM'.",
                        max_length=200,
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text="Short tagline or slogan shown in the app (optional).",
                        max_length=200,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Store Profile",
                "verbose_name_plural": "Store Profile",
            },
        ),
    ]
