# Generated by Django 5.2.8 on 2026-04-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0008_storeprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeprofile",
            name="maps_url",
            field=models.URLField(
                blank=True,
                help_text="Google Maps directions URL for this store location. Paste the full URL from Google Maps (e.g. https://www.google.com/maps/place/...).",
                max_length=2000,
            ),
        ),
    ]
