# Generated by Django 5.2.8 on 2026-04-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0009_storeprofile_maps_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeprofile",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="Latitude coordinate (e.g. 16.7247771). Copy from the Google Maps URL — look for '!3d' followed by the number.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storeprofile",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="Longitude coordinate (e.g. 120.3937788). Copy from the Google Maps URL — look for '!4d' followed by the number.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
