# Generated by Django 5.2.8 on 2026-04-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0010_storeprofile_coords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storeprofile",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="Auto-filled from the Maps URL when you save. Do not edit manually.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="storeprofile",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="Auto-filled from the Maps URL when you save. Do not edit manually.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="storeprofile",
            name="maps_url",
            field=models.URLField(
                blank=True,
                help_text="Paste the full Google Maps URL. Latitude and Longitude will be extracted automatically on save.",
                max_length=2000,
            ),
        ),
    ]
