# Generated by Django 5.2.8 on 2026-04-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0012_reportscheduleconfig_refund_window_days"),
    ]

    operations = [
        migrations.CreateModel(
            name="KioskConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system_name",
                    models.CharField(
                        default="Genglo Printing Services - Self Checkout",
                        help_text="System name shown in the kiosk header, page title, and receipts.",
                        max_length=200,
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        default="Quick, Easy, and Convenient Shopping",
                        help_text="Short tagline shown below the system name in the kiosk header.",
                        max_length=200,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kiosk Config",
                "verbose_name_plural": "Kiosk Config",
            },
        ),
    ]
