# Generated by Django 5.2.8 on 2026-04-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0013_kioskconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="kioskconfig",
            name="receipt_subtitle",
            field=models.CharField(
                default="Self-Checkout Receipt",
                help_text="Subtitle printed on every receipt copy, e.g. 'Self-Checkout Receipt'.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="kioskconfig",
            name="receipt_thank_you",
            field=models.CharField(
                default="Thank you for your purchase!",
                help_text="Thank-you line printed at the bottom of every receipt.",
                max_length=200,
            ),
        ),
    ]
