# Generated by Django 5.2.8 on 2026-04-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0015_kioskconfig_receipt_header_footer"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportscheduleconfig",
            name="return_window_days",
            field=models.PositiveIntegerField(
                default=3,
                help_text="Number of days the member has to physically return the item after a refund is approved (e.g. 3 = 3 days to return). If not returned in time, the refund is automatically voided.",
            ),
        ),
    ]
