# Generated by Django 5.2.8 on 2026-05-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0016_add_return_window_days_to_reportscheduleconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeprofile",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Store logo image (displayed in the mobile app).",
                null=True,
                upload_to="store_logos/",
            ),
        ),
    ]
