# Generated by Django 5.2.8 on 2026-05-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0018_kiosksessionconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kiosksessionconfig",
            name="auto_logout_enabled",
            field=models.BooleanField(
                default=True,
                help_text="When enabled, regular members are logged out after inactivity on /kiosk/. Admin, staff, and cashier sessions are never auto-logged out from idle.",
            ),
        ),
    ]
