# Generated by Django 5.2.8 on 2026-05-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0020_printersettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="kioskconfig",
            name="admin_dashboard_description",
            field=models.TextField(
                default="Monitor real-time performance of Genglo Printing Services. Track sales, members, inventory and member standing from a single super admin console.",
                help_text="Description text shown in the Super Admin dashboard hero section.",
            ),
        ),
    ]
