# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0021_kioskconfig_admin_dashboard_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeprofile",
            name="show_store_name",
            field=models.BooleanField(
                default=True,
                help_text="When enabled, the store name appears on the member login page and in the mobile app (with kiosk system name). When disabled, only the kiosk system name is shown where applicable.",
            ),
        ),
    ]
