# Generated by Django 5.2.16 on 2026-08-23 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0028_remove_kioskconfig_loan_min_membership_months'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('PAGE_ACTION', 'Page Action'), ('MEMBER', 'Members'), ('INVENTORY', 'Inventory'), ('TRANSACTION', 'Transactions'), ('REFUND', 'Refund'), ('LOAN', 'Loans'), ('SAVINGS', 'Savings'), ('PALAY', 'Palay Trade'), ('SETTINGS', 'Settings'), ('REPORT', 'Report / Export'), ('KIOSK', 'Kiosk'), ('ADMIN', 'Django Admin'), ('OTHER', 'Other')], db_index=True, max_length=40)),
                ('actor_label', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('request_method', models.CharField(blank=True, default='', max_length=10)),
                ('request_path', models.CharField(blank=True, default='', max_length=500)),
                ('object_type', models.CharField(blank=True, default='', max_length=80)),
                ('object_id', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Website Audit Log',
                'verbose_name_plural': 'Website Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='admin_panel_action_049d5f_idx'), models.Index(fields=['actor', '-created_at'], name='admin_panel_actor_i_7480d9_idx')],
            },
        ),
    ]
