# Generated by Django 5.2.16 on 2026-08-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0029_websiteauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteauditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('PAGE_ACTION', 'Page Action'), ('MEMBER', 'Members'), ('INVENTORY', 'Inventory'), ('TRANSACTION', 'Transactions'), ('PURCHASE', 'Purchase / Sale'), ('REFUND', 'Refund'), ('BALANCE_REFILL', 'Balance Refill'), ('FUND_TRANSFER', 'Fund Transfer'), ('QR', 'QR Code'), ('CREDIT_PAYMENT', 'Credit Payment'), ('LOAN', 'Loans'), ('SAVINGS', 'Savings'), ('PALAY', 'Palay Trade'), ('SETTINGS', 'Settings'), ('REPORT', 'Report / Export'), ('KIOSK', 'Kiosk'), ('ADMIN', 'Django Admin'), ('OTHER', 'Other')], db_index=True, max_length=40),
        ),
    ]
