# Generated by Django 5.2.16 on 2026-08-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0030_websiteauditlog_security_actions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_rate', models.DecimalField(decimal_places=3, default=0, help_text='Monthly interest rate (%) charged on unpaid credit (utang) principal after the grace period. Example: 2.000 = 2% per month. Set to 0 to disable interest charges.', max_digits=6)),
                ('grace_period_days', models.PositiveIntegerField(default=0, help_text='Days after a credit sale before interest starts. Example: 30 means the member can pay within 30 days with no interest. Set to 0 to start charging from the day after the sale.')),
                ('is_enabled', models.BooleanField(default=False, help_text='When enabled, interest is applied to overdue credit (utang) balances.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credit Settings',
                'verbose_name_plural': 'Credit Settings',
            },
        ),
        migrations.AlterField(
            model_name='kioskconfig',
            name='admin_dashboard_description',
            field=models.TextField(default='Monitor real-time performance of BAGNOS MPC. Track sales, members, inventory and member standing from a single super admin console.', help_text='Description text shown in the Super Admin dashboard hero section.'),
        ),
        migrations.AlterField(
            model_name='kioskconfig',
            name='system_name',
            field=models.CharField(default='BAGNOS MPC - Self Checkout', help_text='System name shown in the kiosk header, page title, and receipts.', max_length=200),
        ),
        migrations.AlterField(
            model_name='storeprofile',
            name='store_name',
            field=models.CharField(default='BAGNOS MPC', help_text='Official store / business name.', max_length=120),
        ),
    ]
