# Generated by Django 5.2.16 on 2026-08-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0031_credit_settings_and_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditsettings',
            name='grace_period_days',
            field=models.PositiveIntegerField(default=3, help_text='Days after a credit sale before interest is applied. Example: 3 means the member can pay within 3 days with no interest; on day 3 (and after), the interest rate is applied once. Set to 0 to apply interest starting the day of the sale.'),
        ),
        migrations.AlterField(
            model_name='creditsettings',
            name='interest_rate',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Interest rate (%) charged once on unpaid credit (utang) principal after the grace period. Example: 5.000 = 5% of remaining balance. Set to 0 to disable interest charges.', max_digits=6),
        ),
    ]
