# Generated by Django 5.2.16 on 2026-08-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0033_credit_interest_monthly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditsettings',
            name='grace_period_days',
            field=models.PositiveIntegerField(default=3, help_text='Days after a credit sale before interest starts. Example: 3 means the member can pay within 3 days with no interest; after that, compound interest applies every unpaid month. Set to 0 to start charging from the day of the sale.'),
        ),
        migrations.AlterField(
            model_name='creditsettings',
            name='interest_rate',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Monthly compound interest rate on unpaid credit (utang) after grace. Enter a decimal (0.015 = 1.5%) or a percent greater than 1 (1.5 = 1.5%). Each unpaid month charges rate on the current total (principal + unpaid interest). Example: ₱10 → ₱10.15 after month 1; month 2 charges on ₱10.15. Set to 0 to disable.', max_digits=6),
        ),
    ]
