# Generated by Django 5.2.16 on 2026-08-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0034_credit_interest_compound_monthly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditsettings',
            name='grace_period_days',
            field=models.PositiveIntegerField(default=3, help_text='Days after a credit sale before interest starts. Example: 3 means the member can pay within 3 days with no interest; after that, principal × rate is added every unpaid month. Set to 0 to start charging from the day of the sale.'),
        ),
        migrations.AlterField(
            model_name='creditsettings',
            name='interest_rate',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Monthly interest rate on unpaid credit (utang) after grace. Enter a decimal (0.015 = 1.5%) or a percent greater than 1 (1.5 = 1.5%). Each unpaid month: interest = remaining principal × rate (same ₱ amount each month). Example: ₱500 → ₱507.50 after month 1; month 2 adds another ₱7.50 → ₱515. Set to 0 to disable.', max_digits=6),
        ),
    ]
