"""
Django settings for coop_kiosk project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Make the helper package importable from anywhere in the project.
# Supports both styles:
#   from helper.members_helper import credit_balance   (package style)
#   from members_helper import credit_balance          (legacy flat style)
_BASE_DIR_STR = str(BASE_DIR)
if _BASE_DIR_STR not in sys.path:
    sys.path.insert(0, _BASE_DIR_STR)
_HELPER_DIR = str(BASE_DIR / 'helper')
if _HELPER_DIR not in sys.path:
    sys.path.insert(1, _HELPER_DIR)

# Settings helper — wires in security, caching, logging, CORS and rate-limiting
from helper.settings_helper import (
    get_secure_database_config,
    get_secure_session_settings,
    get_secure_csrf_settings,
    get_security_middleware_settings,
    get_cache_config,
    get_logging_config,
    get_cors_settings,
    get_rate_limiting_settings,
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SESSION_SECRET', 'django-insecure-7oua%&pbjg344oj597*jt@8avam@_w32=89jm9^uj5k^2y#0g!')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'crispy_forms',
    'crispy_bootstrap5',
    'widget_tweaks',
    'import_export',
    'members',
    'inventory',
    'transactions',
    'kiosk',
    'admin_panel',
    'mobile_api',
    'ingestion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'mobile_api.middleware.MobileAPICSRFExemptMiddleware',  # Bypass CSRF for all /api/mobile/ endpoints
    'mobile_api.middleware.ConnectionOptimizationMiddleware',  # Connection optimization for mobile API
    'mobile_api.middleware.ResilientSessionMiddleware',  # Resilient session middleware (replaces default SessionMiddleware)
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',  # Must be before SecureAdminMiddleware
    'admin_panel.middleware.SecureAdminMiddleware',  # Secure admin panel access (after MessageMiddleware)
    'mobile_api.middleware.BrokenPipeHandlerMiddleware',  # Handle broken pipes gracefully (should be last)
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'coop_kiosk.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'admin_panel.context_processors.kiosk_branding',
            ],
        },
    },
]

WSGI_APPLICATION = 'coop_kiosk.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database — if DATABASE_URL env var is set (production) settings_helper is used;
# otherwise falls back to explicit local MySQL config.
_database_url = os.environ.get('DATABASE_URL')
if _database_url:
    DATABASES = get_secure_database_config(db_url=_database_url)
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'test_01',
            'USER': 'root',
            'PASSWORD': 'root',
            'HOST': '127.0.0.1',
            'PORT': '3307',
            'OPTIONS': {
                'connect_timeout': 20,
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                'charset': 'utf8mb4',
            }
        }
    }

# Primary writer for ingestion bulk_create; default may point at a read replica.
DATABASES['primary'] = {**DATABASES['default']}
_replica_url = os.environ.get('DATABASE_REPLICA_URL')
if _replica_url:
    import dj_database_url

    DATABASES['default'] = dj_database_url.config(
        default=_replica_url,
        conn_max_age=600,
        conn_health_checks=True,
    )

DATABASE_ROUTERS = ['ingestion.db_router.PrimaryReplicaRouter']


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'
CRISPY_TEMPLATE_PACK = 'bootstrap5'

# VAT Configuration
VAT_RATE = .12  # 12% VAT
# If True, product prices / subtotals are assumed to already include VAT and
# the VAT amount should be extracted from the subtotal. If False, VAT is
# calculated on top of the subtotal (exclusive).
VAT_INCLUSIVE = False

# Fixed VAT amount per product line (currency units). When using a fixed VAT
# amount (e.g., 12.00), the per-line VAT will be the smaller of the fixed
# amount and the line total to avoid negative vatable sale.
VAT_FIXED = 12.00

# Product Fee Configuration
# Enable/disable product fee feature (₱0.50 per product)
# Can be toggled via: python manage.py toggle_product_fee --enable/--disable
PRODUCT_FEE_ENABLED = os.environ.get('PRODUCT_FEE_ENABLED', 'False').lower() == 'true'

# Authentication Settings
LOGIN_URL = '/'  # Root login page
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'  # Redirect to login after logout

# REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}
# Rate-limiting — via settings_helper
REST_FRAMEWORK.update(get_rate_limiting_settings()['REST_FRAMEWORK'])

# CORS Settings — via settings_helper (dev: allow all origins; prod: env-controlled)
globals().update(get_cors_settings())

# Session settings — via settings_helper (production adds COOKIE_SECURE + Strict SameSite)
globals().update(get_secure_session_settings())

# CSRF settings — via settings_helper
globals().update(get_secure_csrf_settings())

# Production security headers — via settings_helper (no-op when PRODUCTION != 'true')
globals().update(get_security_middleware_settings())
SECURE_SSL_REDIRECT = False  # Override: no HTTPS redirect in development
USE_TZ = True

# Connection settings for mobile API pipeline tunnel
# These settings optimize connections for mobile app users
DATA_UPLOAD_MAX_MEMORY_SIZE = 2621440  # 2.5 MB - reduce for faster mobile uploads
FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440  # 2.5 MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000

# HTTP Keep-Alive settings
# Note: Connection keep-alive is automatically handled by the HTTP server
# (nginx, Apache, or even Django's development server).
# The HTTP server manages keep-alive based on HTTP version and client capabilities.
# We don't set Connection headers in WSGI responses (they're hop-by-hop headers).

# Logging — via settings_helper (dev: console only; prod: adds rotating file handlers)
LOGGING = get_logging_config()

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('MAIL_SERVER', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('MAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('MAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.environ.get('MAIL_USERNAME', 'bsnmpckat@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('MAIL_PASSWORD', 'okfb xdir tyvl ocbb')
DEFAULT_FROM_EMAIL = os.environ.get('MAIL_DEFAULT_SENDER', 'CARP- COMPREHENSIVE AGRARIAN REFORM PROGRAM <bsnmpckat@gmail.com>')

# Daily Report Email Configuration - Admin email that receives daily reports
ADMIN_EMAIL = os.environ.get('ADMIN_EMAIL', 'bsnmpckat@gmail.com')
DAILY_REPORT_EMAIL = os.environ.get('DAILY_REPORT_EMAIL', ADMIN_EMAIL)


# Cache — via settings_helper (dev: local memory; prod: Redis > Memcached > DB)
CACHES = get_cache_config()

# For production, use Redis (recommended):
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.redis.RedisCache',
#         'LOCATION': 'redis://127.0.0.1:6379/1',
#     }
# }

# Weekly database backups (uses DATABASES above — MySQL or SQLite)
WEEKLY_DB_BACKUP_ENABLED = os.environ.get(
    'WEEKLY_DB_BACKUP_ENABLED', 'True'
).lower() == 'true'
WEEKLY_DB_BACKUP_RETENTION_WEEKS = int(
    os.environ.get('WEEKLY_DB_BACKUP_RETENTION_WEEKS', '52')
)
WEEKLY_DB_BACKUP_DAY_OF_WEEK = os.environ.get('WEEKLY_DB_BACKUP_DAY_OF_WEEK', 'sun')
WEEKLY_DB_BACKUP_HOUR = int(os.environ.get('WEEKLY_DB_BACKUP_HOUR', '2'))
WEEKLY_DB_BACKUP_MINUTE = int(os.environ.get('WEEKLY_DB_BACKUP_MINUTE', '0'))

# MySQL/MariaDB -> backups/mysql_weekly/kiosk_database_2026-W20.sql
MYSQL_WEEKLY_BACKUP_FOLDER = BASE_DIR / 'backups' / 'mysql_weekly'
MYSQLDUMP_PATH = os.environ.get('MYSQLDUMP_PATH', '')  # optional full path to mysqldump.exe

# SQLite -> backups/sqlite_weekly/db_2026-W20.sqlite3 (legacy / dev)
SQLITE_WEEKLY_BACKUP_FOLDER = BASE_DIR / 'backups' / 'sqlite_weekly'
SQLITE_WEEKLY_BACKUP_SOURCE = os.environ.get('SQLITE_WEEKLY_BACKUP_SOURCE', '')
# Back-compat aliases used by scheduler
SQLITE_WEEKLY_BACKUP_ENABLED = WEEKLY_DB_BACKUP_ENABLED
SQLITE_WEEKLY_BACKUP_RETENTION_WEEKS = WEEKLY_DB_BACKUP_RETENTION_WEEKS
SQLITE_WEEKLY_BACKUP_DAY_OF_WEEK = WEEKLY_DB_BACKUP_DAY_OF_WEEK
SQLITE_WEEKLY_BACKUP_HOUR = WEEKLY_DB_BACKUP_HOUR
SQLITE_WEEKLY_BACKUP_MINUTE = WEEKLY_DB_BACKUP_MINUTE

# Google Drive — weekly backups auto-upload after local backup is created
# Folder: https://drive.google.com/drive/folders/1Af2NF1hLssjDqjO_UsRDsalhDoYO9Sw-
# Personal Drive: use oauth + authorize_google_drive (service accounts have no quota)
GOOGLE_DRIVE_AUTH_MODE = os.environ.get('GOOGLE_DRIVE_AUTH_MODE', 'oauth')
GOOGLE_DRIVE_UPLOAD_ENABLED = os.environ.get(
    'GOOGLE_DRIVE_UPLOAD_ENABLED', 'True'
).lower() == 'true'
GOOGLE_DRIVE_FOLDER_ID = os.environ.get(
    'GOOGLE_DRIVE_FOLDER_ID',
    '1Af2NF1hLssjDqjO_UsRDsalhDoYO9Sw-',
)
GOOGLE_DRIVE_OAUTH_CLIENT_JSON = os.environ.get(
    'GOOGLE_DRIVE_OAUTH_CLIENT_JSON',
    str(BASE_DIR / 'google_drive_oauth_client.json'),
)
GOOGLE_DRIVE_TOKEN_JSON = os.environ.get(
    'GOOGLE_DRIVE_TOKEN_JSON',
    str(BASE_DIR / 'google_drive_token.json'),
)
# Use 8090 (not 8000) — Django runserver normally uses port 8000
GOOGLE_DRIVE_OAUTH_PORT = int(os.environ.get('GOOGLE_DRIVE_OAUTH_PORT', '8090'))
GOOGLE_DRIVE_OAUTH_HOST = os.environ.get('GOOGLE_DRIVE_OAUTH_HOST', '127.0.0.1')
# Legacy service account (Workspace Shared Drives only — not personal Gmail)
GOOGLE_DRIVE_SERVICE_ACCOUNT_EMAIL = os.environ.get(
    'GOOGLE_DRIVE_SERVICE_ACCOUNT_EMAIL',
    'dti-233@dtiprojetcs.iam.gserviceaccount.com',
)
GOOGLE_DRIVE_CREDENTIALS_JSON = os.environ.get(
    'GOOGLE_DRIVE_CREDENTIALS_JSON',
    str(BASE_DIR / 'google_drive_service_account.json'),
)

# Performance helpers are initialized in admin_panel/apps.py ready()

# ---------------------------------------------------------------------------
# Celery — ingestion pipeline workers
# ---------------------------------------------------------------------------
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_ALWAYS_EAGER = os.environ.get('CELERY_TASK_ALWAYS_EAGER', 'False').lower() == 'true'

# Ingestion API / batch tuning
INGESTION_API_KEY = os.environ.get('INGESTION_API_KEY', '')
INGESTION_SHARD_COUNT = int(os.environ.get('INGESTION_SHARD_COUNT', '4'))
INGESTION_BUFFER_FLUSH_SIZE = int(os.environ.get('INGESTION_BUFFER_FLUSH_SIZE', '1000'))
INGESTION_BUFFER_FLUSH_INTERVAL = float(os.environ.get('INGESTION_BUFFER_FLUSH_INTERVAL', '3'))

_logs_dir = BASE_DIR / 'logs'
_logs_dir.mkdir(exist_ok=True)
LOGGING.setdefault('handlers', {})
LOGGING['handlers']['ingestion_metrics_file'] = {
    'class': 'logging.handlers.RotatingFileHandler',
    'filename': str(_logs_dir / 'ingestion_metrics.log'),
    'maxBytes': 10 * 1024 * 1024,
    'backupCount': 10,
    'formatter': 'verbose',
    'level': 'INFO',
}
LOGGING.setdefault('loggers', {})
LOGGING['loggers']['ingestion.metrics'] = {
    'handlers': ['console', 'ingestion_metrics_file'],
    'level': 'INFO',
    'propagate': False,
}