# Generated by Django 5.2.16 on 2026-08-20 09:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0024_add_loan_officer_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PalayTradeProduct',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name, e.g. RC222 Premium.', max_length=150)),
                ('code', models.SlugField(help_text='Short unique code, e.g. rc222-premium.', max_length=40, unique=True)),
                ('variety', models.CharField(blank=True, help_text='Rice variety or hybrid name (e.g. IR64, RC222).', max_length=100)),
                ('grade', models.CharField(choices=[('fancy', 'Fancy'), ('premium', 'Premium'), ('grade_1', 'Grade 1'), ('grade_2', 'Grade 2'), ('grade_3', 'Grade 3'), ('broken', 'Broken / reject'), ('other', 'Other')], default='grade_1', max_length=16)),
                ('season', models.CharField(choices=[('any', 'Any season'), ('wet', 'Wet season'), ('dry', 'Dry season')], default='any', max_length=8)),
                ('description', models.TextField(blank=True)),
                ('buy_price_per_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default price the coop pays per kilogram when buying.', max_digits=12)),
                ('sell_price_per_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default price per kilogram when selling from stock.', max_digits=12)),
                ('max_moisture_percent', models.DecimalField(decimal_places=2, default=Decimal('14.00'), help_text='Accepted moisture ceiling (%). Above this, apply moisture deduction.', max_digits=5)),
                ('moisture_deduction_per_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0100'), help_text='Fraction of gross kg deducted per 1% moisture over the max (e.g. 0.01 = 1%).', max_digits=8)),
                ('max_impurity_percent', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Accepted foreign matter / impurity ceiling (%).', max_digits=5)),
                ('impurity_deduction_per_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0100'), help_text='Fraction of gross kg deducted per 1% impurity over the max.', max_digits=8)),
                ('min_quantity_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum kilograms per trade. 0 = no minimum.', max_digits=12)),
                ('max_quantity_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum kilograms per trade. 0 = no maximum.', max_digits=12)),
                ('members_only', models.BooleanField(default=False, help_text='If checked, only cooperative members can trade under this product.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Palay trade product',
                'verbose_name_plural': 'Palay trade products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PalayTrade',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trade_type', models.CharField(choices=[('buy', 'Buy from farmer'), ('sell', 'Sell from stock')], max_length=8)),
                ('party_name', models.CharField(help_text='Farmer or buyer name (filled from member when linked).', max_length=200)),
                ('reference', models.CharField(editable=False, max_length=32, unique=True)),
                ('traded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gross_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moisture_percent', models.DecimalField(decimal_places=2, default=Decimal('14.00'), max_digits=5)),
                ('impurity_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('moisture_deduction_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('impurity_deduction_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per kilogram applied on this ticket.', max_digits=12)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('void', 'Void')], db_index=True, default='posted', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(blank=True, help_text='Linked member when the farmer/buyer is a cooperative member.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='palay_trades', to='members.member')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='palay_trades', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='palay_trade.palaytradeproduct')),
            ],
            options={
                'verbose_name': 'Palay trade',
                'verbose_name_plural': 'Palay trades',
                'ordering': ['-traded_at'],
            },
        ),
    ]
