# Generated by Django 5.2.16 on 2026-08-20 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palay_trade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palaytrade',
            name='impurity_deduction_kg',
        ),
        migrations.RemoveField(
            model_name='palaytrade',
            name='impurity_percent',
        ),
        migrations.RemoveField(
            model_name='palaytrade',
            name='moisture_deduction_kg',
        ),
        migrations.RemoveField(
            model_name='palaytrade',
            name='moisture_percent',
        ),
        migrations.RemoveField(
            model_name='palaytradeproduct',
            name='impurity_deduction_per_percent',
        ),
        migrations.RemoveField(
            model_name='palaytradeproduct',
            name='max_impurity_percent',
        ),
        migrations.RemoveField(
            model_name='palaytradeproduct',
            name='max_moisture_percent',
        ),
        migrations.RemoveField(
            model_name='palaytradeproduct',
            name='moisture_deduction_per_percent',
        ),
    ]
