# Generated by Django 5.2.16 on 2026-08-20 09:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palay_trade', '0002_remove_moisture_impurity'),
    ]

    operations = [
        migrations.AddField(
            model_name='palaytradeproduct',
            name='low_stock_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Warn when stock falls to this level or below. 0 = no low-stock warning.', max_digits=12),
        ),
        migrations.AddField(
            model_name='palaytradeproduct',
            name='stock_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current rice stock in kilograms. Buys add stock; sells reduce stock.', max_digits=14),
        ),
    ]
