# Generated by Django 5.2.16 on 2026-08-20 10:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


def copy_variety_names(apps, schema_editor):
    PalayVariety = apps.get_model("palay_trade", "PalayVariety")
    PalayTradeProduct = apps.get_model("palay_trade", "PalayTradeProduct")
    seen = {}
    for product in PalayTradeProduct.objects.exclude(variety_name=""):
        raw = (product.variety_name or "").strip()
        if not raw:
            continue
        key = raw.casefold()
        variety = seen.get(key)
        if variety is None:
            variety = PalayVariety.objects.filter(name__iexact=raw).first()
            if variety is None:
                variety = PalayVariety.objects.create(name=raw)
            seen[key] = variety
        product.variety = variety
        product.save(update_fields=["variety"])


class Migration(migrations.Migration):

    dependencies = [
        ("palay_trade", "0003_add_rice_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="PalayVariety",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Rice variety or hybrid name (e.g. IR64, RC222).",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Palay variety",
                "verbose_name_plural": "Palay varieties",
                "ordering": ["name"],
            },
        ),
        migrations.RenameField(
            model_name="palaytradeproduct",
            old_name="variety",
            new_name="variety_name",
        ),
        migrations.AddField(
            model_name="palaytradeproduct",
            name="variety",
            field=models.ForeignKey(
                blank=True,
                help_text="Rice variety or hybrid. Use Add another variety if it is not in the list yet.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="palay_trade.palayvariety",
            ),
        ),
        migrations.RunPython(copy_variety_names, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="palaytradeproduct",
            name="variety_name",
        ),
    ]
