# Generated by Django 5.2.16 on 2026-08-28 07:13

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShareCapitalProduct',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.SlugField(help_text='Short unique code, e.g. common-share, preferred.', max_length=40, unique=True)),
                ('description', models.TextField(blank=True)),
                ('par_value', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Value of one share in pesos.', max_digits=12)),
                ('min_shares', models.PositiveIntegerField(default=1, help_text='Minimum number of shares a member must hold.')),
                ('max_shares', models.PositiveIntegerField(default=0, help_text='Maximum shares a member may hold. 0 = no limit.')),
                ('min_contribution', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum paid-up amount to start (opening contribution). 0 = any amount.', max_digits=12)),
                ('dividend_rate', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Annual dividend rate in percent (e.g. 5.000 = 5%).', max_digits=6)),
                ('allows_withdrawal', models.BooleanField(default=False, help_text='Share capital is usually locked. Check only if withdrawals are allowed.')),
                ('required_for_membership', models.BooleanField(default=True, help_text='Members are expected to hold this product.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Share capital product',
                'verbose_name_plural': 'Share capital products',
                'ordering': ['name'],
            },
        ),
    ]
