# Generated by Django 5.2 on 2025-11-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="expiration_date",
            field=models.DateField(
                blank=True,
                help_text="Product expiration date for safety tracking",
                null=True,
            ),
        ),
    ]
