# Generated by Django 5.2 on 2025-11-26 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_product_expiration_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="expiration_date",
        ),
    ]
