# Generated by Django 5.2.8 on 2026-04-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_remove_expiration_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="barcode_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload a QR code or barcode image for this product",
                null=True,
                upload_to="products/barcodes/",
            ),
        ),
    ]
