# Generated by Django 5.2.8 on 2026-04-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_add_barcode_image_to_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="barcode_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/barcodes/"
            ),
        ),
    ]
