# Generated by Django 5.2.8 on 2026-05-13 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_alter_product_barcode_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Short label (e.g. "Member weekend 10%").',
                        max_length=200,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional. Blank = no start limit.",
                        null=True,
                    ),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional. Blank = no end date.",
                        null=True,
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percent off list price (e.g. 15.00 = 15%). Leave blank if using fixed amount.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Fixed amount off each unit. Leave blank if using percent.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product discount",
                "verbose_name_plural": "Product discounts",
                "ordering": ["-created_at"],
            },
        ),
    ]
