# Generated by Django 5.2.8 on 2026-05-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_product_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "— (none)"),
                    ("dairy_1l_500ml", "Dairy — 1L or 500ml only"),
                    ("dairy_250ml", "Dairy — 250ml only"),
                    ("pastillas", "Pastillas"),
                    ("espasol_polvoron", "Espasol & Polvoron"),
                ],
                default="",
                help_text="Used for fixed-peso member / senior–PWD discounts at checkout. Example: dairy 1L/500ml vs 250ml, Pastillas, Espasol & Polvoron.",
                max_length=32,
            ),
        ),
    ]
