# Generated by Django 6.0.5 on 2026-05-14 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_product_discount_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_group',
            field=models.ForeignKey(blank=True, help_text='Used for fixed-peso member / senior–PWD discounts at checkout. Edit group display names under Inventory → Product discount groups.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.productdiscountgroup'),
        ),
        migrations.AlterField(
            model_name='productdiscountgroup',
            name='code',
            field=models.CharField(db_index=True, help_text='Stable key used at checkout and in APIs (changing it breaks product links).', max_length=32, unique=True),
        ),
    ]
