# Generated by Django 4.2.30 on 2026-06-18 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_enable_giveaway_all_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Label shown on receipts and admin (e.g. "VAT 12%", "Tax Exempt").', max_length=100, unique=True)),
                ('rate', models.DecimalField(decimal_places=4, default=0.0, help_text='Tax rate as a percentage (e.g. 12.0000 = 12%). Use 0 for tax-exempt.', max_digits=6)),
                ('tax_type', models.CharField(choices=[('inclusive', 'Inclusive — tax is already embedded in the price'), ('exclusive', 'Exclusive — tax is added on top of the price')], default='inclusive', help_text='Inclusive: price already contains the tax. Exclusive: tax is added on top.', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, help_text='Optional internal notes (e.g. BIR code, applicable product categories).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tax rate',
                'verbose_name_plural': 'Tax rates',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.ForeignKey(blank=True, help_text='Tax rule applied to this product at checkout.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.taxrate'),
        ),
    ]
