# Generated by Django 4.2.30 on 2026-07-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_productsaleunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Purchase / cost price per piece (₱). Used for margin tracking.', max_digits=10, verbose_name='Buying price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Retail / list selling price per piece (₱).', max_digits=10, verbose_name='Selling price'),
        ),
    ]
