# Generated by Django 4.2.30 on 2026-07-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_product_price_cost_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstockbatch',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Buying / purchase cost per unit for this stock tier (₱).', max_digits=10, verbose_name='Buying price'),
        ),
        migrations.AlterField(
            model_name='productstockbatch',
            name='tier',
            field=models.CharField(choices=[('old', 'Old stock'), ('new', 'New stock')], help_text='Old stock = remaining units. New stock = units received at the current buying price.', max_length=10),
        ),
    ]
