# Generated by Django 4.2.30 on 2026-07-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_productstockbatch_cost_buying_price_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstockbatch',
            name='tier',
            field=models.CharField(choices=[('old', 'Old stock'), ('new', 'New stock')], help_text='Old stock = remaining units. New stock = newly received units.', max_length=10),
        ),
        migrations.AlterField(
            model_name='productstockbatch',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Selling price per unit for this stock tier (₱).', max_digits=10, verbose_name='Selling price'),
        ),
    ]
