# Generated by Django 5.2.16 on 2026-08-25 05:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_productstockhistory_price_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('piece', 'By piece'), ('kilo', 'By kilogram')], db_index=True, default='piece', help_text='By piece = counted units. By kilogram = weighable goods with decimal kg stock.', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Purchase / cost price per piece or per kg (₱). Used for margin tracking.', max_digits=10, verbose_name='Buying price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='low_stock_threshold',
            field=models.DecimalField(decimal_places=3, default=10, help_text='Low-stock warning level in pieces or kilograms.', max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Retail / list selling price per piece or per kg (₱).', max_digits=10, verbose_name='Selling price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=3, default=0, help_text='On-hand quantity in pieces or kilograms, matching unit type.', max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productsaleunit',
            name='sale_mode',
            field=models.CharField(choices=[('retail', 'By piece (retail)'), ('wholesale', 'Wholesale (box / bulk)')], default='retail', help_text='Retail = sold per piece or per kg. Wholesale = sold per box, pack, or case.', max_length=20),
        ),
        migrations.AlterField(
            model_name='productsaleunit',
            name='unit_label',
            field=models.CharField(help_text='Shown on receipts and admin (e.g. "Piece", "Kilogram", "Box of 12").', max_length=50),
        ),
        migrations.AlterField(
            model_name='productsaleunit',
            name='units_per_package',
            field=models.PositiveIntegerField(default=1, help_text='Base stock units consumed per 1 of this sale unit. Use 1 for per-piece or per-kg; e.g. 12 when one box contains 12 pencils.'),
        ),
        migrations.AlterField(
            model_name='productstockbatch',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Buying / purchase cost per piece or per kg for this stock tier (₱).', max_digits=10, verbose_name='Buying price'),
        ),
        migrations.AlterField(
            model_name='productstockbatch',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Units on hand in this tier (pieces or kilograms).', max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productstockbatch',
            name='tier',
            field=models.CharField(choices=[('old', 'Old stock'), ('new', 'New stock')], help_text='Old stock = remaining units. New stock = newly received units. Quantities are pieces or kg.', max_length=10),
        ),
        migrations.AlterField(
            model_name='productstockbatch',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Selling price per piece or per kg for this stock tier (₱).', max_digits=10, verbose_name='Selling price'),
        ),
        migrations.AlterField(
            model_name='productstockhistory',
            name='new_stock_after',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='productstockhistory',
            name='new_stock_before',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='productstockhistory',
            name='old_stock_after',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='productstockhistory',
            name='old_stock_before',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='productstockhistory',
            name='quantity_sold',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Units sold in this event (only for sale changes).', max_digits=14),
        ),
        migrations.AlterField(
            model_name='productstockhistory',
            name='total_after',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='productstockhistory',
            name='total_before',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='stock_after',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='stock_before',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
    ]
