# Generated by Django 5.2.3 on 2025-11-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transactionitem_vat_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='vatable_sale',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
