# Generated by Django 5.2.3 on 2025-11-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_vatable_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='vatable_sale',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
