# Generated by Django 5.2.8 on 2025-12-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0004_transactionitem_vatable_sale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="amount_to_utang",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="patronage_amount",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="patronage_rate",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payment_method",
            field=models.CharField(
                choices=[("debit", "Debit (Member Account)"), ("cash", "Cash")],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="PatronageDistribution",
        ),
    ]
