# Generated by Django 5.2.8 on 2026-04-28 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0009_add_refund_requested_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transactionitem",
            options={},
        ),
        migrations.CreateModel(
            name="RefundReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason_type",
                    models.CharField(
                        choices=[
                            ("defective", "Defective / Damaged Product"),
                            ("wrong_item", "Wrong Item Received"),
                            ("change_of_mind", "Change of Mind"),
                            ("overcharged", "Overcharged / Billing Error"),
                            ("duplicate", "Duplicate Transaction"),
                            (
                                "product_unavailable",
                                "Product Unavailable / Out of Stock",
                            ),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                        verbose_name="Reason Category",
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        help_text="Describe the specific reason for the refund request.",
                        verbose_name="Additional Details",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refund_reason",
                        to="transactions.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction Item",
                "verbose_name_plural": "Transaction Items",
            },
        ),
    ]
