# Generated by Django 5.2.8 on 2026-04-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0010_add_refundreason_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refundreason",
            name="reason_type",
            field=models.CharField(
                choices=[
                    ("defective", "Defective / Damaged Product"),
                    ("wrong_item", "Wrong Item Received"),
                    ("change_of_mind", "Change of Mind"),
                    ("overcharged", "Overcharged / Billing Error"),
                    ("duplicate", "Duplicate Transaction"),
                    ("not_received", "Item Not Received"),
                    ("product_unavailable", "Product Unavailable / Out of Stock"),
                    ("expired", "Expired Product"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
                verbose_name="Reason Category",
            ),
        ),
    ]
