# Generated by Django 5.2.8 on 2026-04-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0011_add_not_received_reason_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="refundreason",
            name="refund_items",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific items the member wants refunded. Empty means all items.",
                related_name="refund_reasons",
                to="transactions.transactionitem",
                verbose_name="Items to Refund",
            ),
        ),
    ]
