# Generated by Django 5.2.8 on 2026-04-30 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0012_add_refund_items_to_refundreason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("refund_requested", "Refund Requested"),
                    ("return_window", "Return Window (Awaiting Item)"),
                    ("refunded", "Refunded"),
                    ("return_expired", "Return Expired (No Refund)"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="RefundReturnWindow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approved_at", models.DateTimeField(auto_now_add=True)),
                ("return_deadline", models.DateTimeField()),
                ("is_returned", models.BooleanField(default=False)),
                ("return_confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_return_windows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_window",
                        to="transactions.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Refund Return Window",
                "verbose_name_plural": "Refund Return Windows",
            },
        ),
    ]
