# Generated by Django 5.2.8 on 2026-05-14 03:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0014_transactionitem_manual_discount_php"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="refundreason",
            options={
                "verbose_name": "Refund Reason",
                "verbose_name_plural": "Refund Reasons",
            },
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="transactionitem",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
