# Generated by Django 5.2.8 on 2026-05-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0015_transaction_created_at_editable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_number",
            field=models.CharField(
                blank=True,
                help_text="Leave blank when creating in admin; a unique TXN number is assigned on save.",
                max_length=50,
                unique=True,
            ),
        ),
    ]
