# Generated by Django 4.2.30 on 2026-07-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0025_transaction_processed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('debit', 'Debit (Member Account)'), ('credit', 'Credit (Utang)'), ('cash', 'Cash')], max_length=20),
        ),
    ]
