# Generated by Django 5.2.16 on 2026-08-25 00:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0026_alter_transaction_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpayment',
            name='interest_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Portion of amount_paid applied to credit interest.', max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='credit_interest_accrued',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total interest charged on this credit sale (after grace period).', max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='credit_interest_last_applied_on',
            field=models.DateField(blank=True, help_text='Date of the last monthly interest accrual for this sale.', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='credit_interest_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Interest amount already paid toward this credit sale.', max_digits=12),
        ),
    ]
