# Generated by Django 5.2.16 on 2026-08-25 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0027_credit_settings_and_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='credit_interest_last_applied_on',
            field=models.DateField(blank=True, help_text='Date when one-time interest was applied after the grace period.', null=True),
        ),
    ]
