# Generated by Django 5.2.16 on 2026-08-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0028_credit_interest_helptext_one_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='credit_interest_last_applied_on',
            field=models.DateField(blank=True, help_text='Date when credit interest was last applied (monthly accrual).', null=True),
        ),
    ]
