# Generated by Django 5.2.16 on 2026-08-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0029_credit_interest_monthly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='credit_interest_last_applied_on',
            field=models.DateField(blank=True, help_text='Date of the last monthly compound interest period applied.', null=True),
        ),
    ]
