# Generated by Django 5.2.16 on 2026-08-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0031_credit_interest_simple_monthly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=14),
        ),
    ]
