# Generated by Django 5.2.16 on 2026-07-26 01:24

import django.db.models.deletion
import django.utils.timezone
import django_fsm
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('interest_rate', models.DecimalField(decimal_places=3, help_text='Annual interest rate, percent.', max_digits=6)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('requires_collateral', models.BooleanField(default=False)),
                ('requires_insurance', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purpose', models.TextField(blank=True)),
                ('term_months', models.PositiveIntegerField(default=12)),
                ('status', django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_VERIFICATION', 'Under Verification'), ('VERIFICATION_FAILED', 'Verification Failed'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('PENDING_COMMITTEE_APPROVAL', 'Pending Committee Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('INSURANCE_ENROLLED', 'Insurance Enrolled'), ('DOCUMENTATION_SIGNED', 'Documentation Signed'), ('DISBURSED', 'Disbursed'), ('ACTIVE', 'Active'), ('FULLY_PAID', 'Fully Paid'), ('CLOSED', 'Closed')], default='DRAFT', max_length=50, protected=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to=settings.AUTH_USER_MODEL)),
                ('loan_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='loans.loanproduct')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_verify', 'Can verify loan application eligibility'), ('can_investigate', 'Can perform credit investigation'), ('can_approve', 'Can approve/reject loan applications (committee)'), ('can_disburse', 'Can disburse approved loans'), ('can_collect_payment', 'Can collect loan repayments')],
            },
        ),
        migrations.CreateModel(
            name='InsuranceEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurance_type', models.CharField(choices=[('CREDIT_LIFE', 'Credit Life')], default='CREDIT_LIFE', max_length=30)),
                ('premium_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('payment_mode', models.CharField(choices=[('COLLECTED', 'Collected Upfront'), ('FINANCED', 'Financed Into Loan')], max_length=20)),
                ('enrolled_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_enrollment', to='loans.loanapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EligibilityVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership_status_ok', models.BooleanField(default=False)),
                ('documents_complete', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_done', to=settings.AUTH_USER_MODEL)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_verification', to='loans.loanapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_released', models.DecimalField(decimal_places=2, max_digits=12)),
                ('disbursement_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('disbursement_method', models.CharField(choices=[('CASH', 'Cash'), ('CHECK', 'Check'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('disbursed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursements_made', to=settings.AUTH_USER_MODEL)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disbursement', to='loans.loanapplication')),
            ],
            options={
                'ordering': ['-disbursement_date'],
            },
        ),
        migrations.CreateModel(
            name='DelinquencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('days_overdue', models.PositiveIntegerField(default=0)),
                ('amount_overdue', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('flagged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delinquency_records', to='loans.loanapplication')),
            ],
            options={
                'ordering': ['-flagged_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repayment_capacity_score', models.PositiveSmallIntegerField(default=0)),
                ('loan_purpose_assessment', models.TextField(blank=True)),
                ('recommendation', models.CharField(choices=[('RECOMMEND_APPROVE', 'Recommend Approve'), ('RECOMMEND_DENY', 'Recommend Deny')], max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('evaluated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigations_done', to=settings.AUTH_USER_MODEL)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_investigation', to='loans.loanapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('reviewed_by', models.ManyToManyField(related_name='committee_reviews', to=settings.AUTH_USER_MODEL)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='committee_review', to='loans.loanapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_released', models.BooleanField(default=False)),
                ('release_notes', models.TextField(blank=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaterals', to='loans.loanapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AmortizationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installment_number', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('principal_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fees_due', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amortization_schedules', to='loans.loanapplication')),
            ],
            options={
                'ordering': ['application', 'installment_number'],
                'unique_together': {('application', 'installment_number')},
            },
        ),
        migrations.CreateModel(
            name='LoanDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement_file', models.FileField(blank=True, upload_to='loan_agreements/%Y/%m/')),
                ('signed_by_borrower_at', models.DateTimeField(blank=True, null=True)),
                ('signed_by_authorized_personnel_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documentation', to='loans.loanapplication')),
                ('witnessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='witnessed_documentations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_inquiries', to=settings.AUTH_USER_MODEL)),
                ('staff_handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_inquiries', to=settings.AUTH_USER_MODEL)),
                ('loan_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='loans.loanproduct')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closure_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('clearance_issued', models.BooleanField(default=False)),
                ('clearance_document', models.FileField(blank=True, upload_to='clearance_certificates/%Y/%m/')),
                ('collateral_released', models.BooleanField(default=False)),
                ('collateral_release_notes', models.TextField(blank=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='loans.loanapplication')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements_closed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-closure_date'],
            },
        ),
        migrations.CreateModel(
            name='LumpSumPayoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maturity_date', models.DateField()),
                ('total_amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lump_sum_payoff', to='loans.loanapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(default='EMAIL', max_length=30)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='loans.loanapplication')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CHECK', 'Check'), ('ONLINE', 'Online'), ('DEDUCTION', 'Payroll/Share Deduction')], max_length=20)),
                ('or_number', models.CharField(blank=True, max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loans.loanapplication')),
                ('applied_to_installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='loans.amortizationschedule')),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_collected', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option', models.CharField(choices=[('LUMP_SUM', 'Lump Sum'), ('MONTHLY_AMORTIZATION', 'Monthly Amortization')], max_length=30)),
                ('selected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_option', to='loans.loanapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(max_length=100)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('loan_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='loans.loanproduct')),
            ],
            options={
                'ordering': ['loan_product', 'document_type'],
            },
        ),
        migrations.CreateModel(
            name='SubmittedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='loan_documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_documents', to='loans.loanapplication')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
