# Generated by Django 5.2.16 on 2026-07-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanproduct',
            name='interest_start_month',
            field=models.PositiveIntegerField(default=1, help_text='Installment month when interest starts applying (1 = first month). Earlier installments have ₱0 interest; interest is added from this month onward.'),
        ),
    ]
