# Generated by Django 5.2.16 on 2026-07-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanproduct_interest_start_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanproduct',
            name='interest_rate',
            field=models.DecimalField(decimal_places=3, help_text='Late-payment interest rate (annual %). Applied only when an installment is not paid on or before its due date.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='interest_start_month',
            field=models.PositiveIntegerField(default=1, help_text='First installment month that can receive late interest if unpaid past due (1 = first month). Earlier months stay interest-free even when late.'),
        ),
    ]
