# Generated by Django 5.2.16 on 2026-07-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loanproduct_late_interest_helptext'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanproduct',
            name='term_months',
            field=models.PositiveIntegerField(default=12, help_text='Fixed repayment term in months for this product (set by admin only).'),
        ),
    ]
