# Generated by Django 5.2.16 on 2026-07-26 04:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loanproduct_term_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditinvestigation',
            name='repayment_capacity_score',
            field=models.DecimalField(decimal_places=1, default=Decimal('100.0'), help_text="Starts at 100. Reduced by 0.1 for each unpaid overdue installment on the member's previous loan applications.", max_digits=6),
        ),
    ]
