# Generated by Django 5.2.16 on 2026-08-20 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_loancommitteevote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplicationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('APPLICATION_CREATED', 'Application Created'), ('APPLICATION_SUBMITTED', 'Application Submitted'), ('STATUS_CHANGED', 'Status Changed'), ('ELIGIBILITY_REVIEW', 'Eligibility Review'), ('CREDIT_INVESTIGATION', 'Credit Investigation'), ('COMMITTEE_VOTE', 'Committee Vote'), ('COMMITTEE_FINALIZED', 'Committee Finalized'), ('INSURANCE_ENROLLED', 'Insurance Enrolled'), ('DOCUMENTATION_SIGNED', 'Documentation Signed'), ('DISBURSEMENT', 'Disbursement'), ('PAYMENT_OPTION', 'Payment Option Selected'), ('PAYMENT_RECORDED', 'Payment Recorded'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('STEP_ACCESS_BLOCKED', 'Blocked Step Access'), ('SECURITY_ACTION_BLOCKED', 'Blocked Security Action'), ('NOTIFICATION_SENT', 'Notification Sent')], db_index=True, max_length=40)),
                ('actor_label', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_audit_entries', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='loans.loanapplication')),
            ],
            options={
                'verbose_name': 'Loan Application Audit Log',
                'verbose_name_plural': 'Loan Application Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['application', '-created_at'], name='loans_loana_applica_b4e82f_idx')],
            },
        ),
    ]
