# Generated by Django 5.2.16 on 2026-08-20 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0011_loanapplicationauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loandocumentation',
            name='signed_hard_copy',
            field=models.FileField(blank=True, help_text='Scanned or photographed signed paper contract kept for security.', null=True, upload_to='loan_hard_copies/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='loandocumentation',
            name='signed_hard_copy_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loandocumentation',
            name='signed_hard_copy_uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_loan_hard_copies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loandocumentation',
            name='signing_method',
            field=models.CharField(choices=[('DIGITAL', 'On-screen signatures'), ('HARD_COPY', 'Uploaded signed hard copy')], default='DIGITAL', help_text='How the contract was executed: drawn on screen or scanned paper original.', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplicationauditlog',
            name='action',
            field=models.CharField(choices=[('APPLICATION_CREATED', 'Application Created'), ('APPLICATION_SUBMITTED', 'Application Submitted'), ('STATUS_CHANGED', 'Status Changed'), ('ELIGIBILITY_REVIEW', 'Eligibility Review'), ('CREDIT_INVESTIGATION', 'Credit Investigation'), ('COMMITTEE_VOTE', 'Committee Vote'), ('COMMITTEE_FINALIZED', 'Committee Finalized'), ('INSURANCE_ENROLLED', 'Insurance Enrolled'), ('DOCUMENTATION_SIGNED', 'Documentation Signed'), ('SIGNED_HARD_COPY_UPLOADED', 'Signed Hard Copy Uploaded'), ('DISBURSEMENT', 'Disbursement'), ('PAYMENT_OPTION', 'Payment Option Selected'), ('PAYMENT_RECORDED', 'Payment Recorded'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('STEP_ACCESS_BLOCKED', 'Blocked Step Access'), ('SECURITY_ACTION_BLOCKED', 'Blocked Security Action'), ('NOTIFICATION_SENT', 'Notification Sent')], db_index=True, max_length=40),
        ),
    ]
