# Generated by Django 5.2.16 on 2026-08-25 14:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0013_loanapplication_interest_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanproduct',
            name='interest_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Legacy product default late-payment interest rate (annual %). The rate used for each loan is set on the application at apply time.', max_digits=6),
        ),
    ]
