# Generated by Django 5.2.16 on 2026-08-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0014_loanproduct_interest_rate_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanproduct',
            name='requires_insurance',
            field=models.BooleanField(default=False),
        ),
    ]
