# Generated by Django 5.2.3 on 2025-11-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='pin_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
