# Generated by Django 5.2.8 on 2025-12-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_member_pin_hash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="balancetransaction",
            name="utang_after",
        ),
        migrations.RemoveField(
            model_name="balancetransaction",
            name="utang_before",
        ),
        migrations.RemoveField(
            model_name="member",
            name="total_patronage",
        ),
        migrations.RemoveField(
            model_name="member",
            name="utang_balance",
        ),
        migrations.RemoveField(
            model_name="membertype",
            name="patronage_rate",
        ),
        migrations.AlterField(
            model_name="balancetransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("deposit", "Deposit"), ("deduction", "Deduction")],
                max_length=20,
            ),
        ),
    ]
