# Generated by Django 5.2.8 on 2025-12-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_remove_balancetransaction_utang_after_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("cashier", "Cashier"),
                    ("staff", "Staff"),
                    ("member", "Member"),
                ],
                default="member",
                max_length=20,
            ),
        ),
    ]
