# Generated by Django 5.2.8 on 2025-12-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_alter_member_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletedMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_id",
                    models.IntegerField(help_text="Original member ID before deletion"),
                ),
                ("rfid_card_number", models.CharField(max_length=50)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "member_type_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("role", models.CharField(max_length=20)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("username", models.CharField(blank=True, max_length=150, null=True)),
                ("pin_hash", models.CharField(blank=True, max_length=128, null=True)),
                ("deleted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True,
                        help_text="Username of person who deleted",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "deletion_reason",
                    models.TextField(
                        blank=True, help_text="Optional reason for deletion"
                    ),
                ),
                ("original_created_at", models.DateTimeField(blank=True, null=True)),
                ("original_updated_at", models.DateTimeField(blank=True, null=True)),
                ("original_date_joined", models.DateTimeField(blank=True, null=True)),
                (
                    "original_last_transaction",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("restored", models.BooleanField(default=False)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                (
                    "restored_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
            ],
            options={
                "verbose_name": "Deleted Member",
                "verbose_name_plural": "Deleted Members",
                "ordering": ["-deleted_at"],
            },
        ),
    ]
