# Generated by Django 5.2.8 on 2026-04-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_deletedmember"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="is_pin_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="member",
            name="pin_attempts",
            field=models.IntegerField(default=0),
        ),
    ]
