# Generated by Django 5.2.8 on 2026-04-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0006_add_pin_lockout_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
