# Generated by Django 5.2.8 on 2026-04-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_add_username_to_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="app_password_hash",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
