# Generated by Django 5.2.8 on 2026-04-19 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0008_add_app_password_to_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="app_password_hash",
        ),
    ]
