# Generated by Django 5.2.8 on 2026-04-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0009_remove_member_app_password_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="rfid_card_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
