# Generated by Django 5.2.8 on 2026-04-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0010_rfid_card_number_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deletedmember",
            name="rfid_card_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
