# Generated by Django 5.2.8 on 2026-05-05 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0014_alter_cardbalancerefill_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cardbalancerefill",
            name="reversal_balance_transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="card_refill_reversal",
                to="members.balancetransaction",
            ),
        ),
        migrations.AddField(
            model_name="cardbalancerefill",
            name="reversed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cardbalancerefill",
            name="reversed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reversed_balance_refills",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
