# Generated by Django 5.2.8 on 2026-05-05 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0015_cardbalancerefill_reversal_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membertype",
            options={
                "verbose_name": "Member type",
                "verbose_name_plural": "Member types",
            },
        ),
    ]
