# Generated by Django 5.2.8 on 2026-05-11 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0016_alter_membertype_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberEditHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=150, null=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "rfid_card_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("role", models.CharField(blank=True, max_length=32)),
                ("edited_at", models.DateTimeField(auto_now_add=True)),
                ("edited_by", models.CharField(blank=True, max_length=150)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edit_history",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member Edit History",
                "verbose_name_plural": "Member Edit Histories",
                "ordering": ["-edited_at"],
            },
        ),
    ]
