# Generated by Django 5.2.8 on 2026-05-13 10:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def seed_concession_policies(apps, schema_editor):
    Policy = apps.get_model('members', 'ConcessionDiscountPolicy')
    defaults = [
        ('senior', Decimal('20.00')),
        ('pwd', Decimal('20.00')),
    ]
    for slug, pct in defaults:
        if not Policy.objects.filter(slug=slug).exists():
            Policy.objects.create(slug=slug, discount_percent=pct, is_active=True)


def unseed_concession_policies(apps, schema_editor):
    Policy = apps.get_model('members', 'ConcessionDiscountPolicy')
    Policy.objects.filter(slug__in=['senior', 'pwd']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0017_memberedithisory"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConcessionDiscountPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        choices=[
                            ("senior", "Senior citizen"),
                            ("pwd", "PWD (Person with disability)"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20.00"),
                        help_text="Percent off the product list price for eligible members.",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Concession discount policy",
                "verbose_name_plural": "Concession discount policies",
            },
        ),
        migrations.CreateModel(
            name="PWDProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to suspend PWD benefits without deleting the record.",
                    ),
                ),
                (
                    "pwd_id_number",
                    models.CharField(
                        blank=True,
                        help_text="Optional PWD ID reference for your records.",
                        max_length=64,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pwd_profile",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "PWD profile",
                "verbose_name_plural": "PWD profiles",
            },
        ),
        migrations.CreateModel(
            name="SeniorCitizenProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to suspend senior benefits without deleting the record.",
                    ),
                ),
                (
                    "osca_id_number",
                    models.CharField(
                        blank=True,
                        help_text="Optional OSCA / ID reference for your records.",
                        max_length=64,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="senior_profile",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Senior citizen profile",
                "verbose_name_plural": "Senior citizen profiles",
            },
        ),
        migrations.RunPython(seed_concession_policies, unseed_concession_policies),
    ]
