# Generated by Django 5.2.8 on 2026-05-13 10:27

from decimal import Decimal

from django.db import migrations, models


def seed_segment_discounts(apps, schema_editor):
    M = apps.get_model('members', 'SegmentProductGroupDiscount')
    rows = [
        ('senior_pwd', 'dairy_1l_500ml', Decimal('5'), 'Senior/PWD — dairy (₱5 off)'),
        ('senior_pwd', 'dairy_250ml', Decimal('5'), 'Senior/PWD — dairy (₱5 off)'),
        ('member_reseller', 'dairy_1l_500ml', Decimal('10'), 'Member — dairy 1L/500ml (₱10 off)'),
        ('member_reseller', 'dairy_250ml', Decimal('5'), 'Member — dairy 250ml (₱5 off)'),
        ('member_reseller', 'pastillas', Decimal('10'), 'Member — Pastillas (₱10 off)'),
        ('member_reseller', 'espasol_polvoron', Decimal('5'), 'Member — Espasol & Polvoron (₱5 off)'),
    ]
    for seg, grp, amt, lbl in rows:
        if not M.objects.filter(segment=seg, discount_group=grp).exists():
            M.objects.create(
                segment=seg,
                discount_group=grp,
                amount_off=amt,
                label=lbl,
                is_active=True,
            )


def unseed_segment_discounts(apps, schema_editor):
    M = apps.get_model('members', 'SegmentProductGroupDiscount')
    M.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0018_senior_pwd_concession_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="SegmentProductGroupDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("senior_pwd", "Seniors and PWDs"),
                            ("member_reseller", "Members / resellers"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "discount_group",
                    models.CharField(
                        choices=[
                            ("dairy_1l_500ml", "Dairy — 1L or 500ml only"),
                            ("dairy_250ml", "Dairy — 250ml only"),
                            ("pastillas", "Pastillas"),
                            ("espasol_polvoron", "Espasol & Polvoron"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "amount_off",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Pesos deducted per unit after promotional discounts are applied.",
                        max_digits=10,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Optional label on receipts (defaults to amount off).",
                        max_length=160,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Segment product discount",
                "verbose_name_plural": "Segment product discounts",
                "ordering": ["segment", "discount_group"],
                "unique_together": {("segment", "discount_group")},
            },
        ),
        migrations.RunPython(seed_segment_discounts, unseed_segment_discounts),
    ]
