# Generated by Django 5.2.16 on 2026-08-20 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_add_committee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, help_text='Registration date and time. Saved automatically when the member is created and used to determine loan eligibility.'),
        ),
    ]
