# Generated by Django 5.2.16 on 2026-08-20 02:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_member_date_joined_loan_eligibility_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Exact registration date and time. Used to determine loan eligibility.'),
        ),
    ]
