# Generated by Django 5.2.16 on 2026-08-24 10:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_member_inactive_remark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedmember',
            name='share_capital',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='member',
            name='share_capital',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current paid-up share capital balance for this member.', max_digits=12),
        ),
        migrations.CreateModel(
            name='ShareCapitalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(db_index=True, editable=False, help_text='Unique reference for this share-capital ledger row.', max_length=32, unique=True)),
                ('transaction_type', models.CharField(choices=[('opening', 'Opening deposit'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('adjustment', 'Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_capital_transactions', to='members.member')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_capital_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Share Capital Transaction',
                'verbose_name_plural': 'Share Capital Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
