# Generated by Django 5.2.16 on 2026-08-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_member_share_capital'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='annual_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='area',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='member',
            name='barangay',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='member',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('separated', 'Separated'), ('live_in', 'Live-in')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='coop_type',
            field=models.CharField(blank=True, default='', help_text='Membership / farm type classification.', max_length=100, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='member',
            name='date_accepted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='date_of_mf_recog',
            field=models.DateField(blank=True, null=True, verbose_name='Date of MF Recog'),
        ),
        migrations.AddField(
            model_name='member',
            name='date_of_pmes',
            field=models.DateField(blank=True, null=True, verbose_name='Date of PMES'),
        ),
        migrations.AddField(
            model_name='member',
            name='educational_attainment',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='income_sources',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Sources'),
        ),
        migrations.AddField(
            model_name='member',
            name='initial_capital_paid_up',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Initial capital paid-up'),
        ),
        migrations.AddField(
            model_name='member',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_status',
            field=models.CharField(blank=True, default='', help_text='Membership status label (separate from account active flag).', max_length=100, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='member',
            name='mf_center',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='MF Center'),
        ),
        migrations.AddField(
            model_name='member',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='municipality',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='member',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='member',
            name='or_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='OR number'),
        ),
        migrations.AddField(
            model_name='member',
            name='other_assets',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='member',
            name='province',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='member',
            name='religion',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='resolution_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Res. No.'),
        ),
        migrations.AddField(
            model_name='member',
            name='rsbsa_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='RSBSA number'),
        ),
        migrations.AddField(
            model_name='member',
            name='rsbsa_remarks',
            field=models.TextField(blank=True, default='', verbose_name='Remarks (RSBSA)'),
        ),
        migrations.AddField(
            model_name='member',
            name='spouse_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name of spouse / live-in partner'),
        ),
        migrations.AddField(
            model_name='member',
            name='spouse_occupation',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='member',
            name='tin',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='TIN'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Contact number'),
        ),
    ]
