# Generated by Django 5.2.16 on 2026-08-25 08:48

import django.db.models.deletion
from django.db import migrations, models


def seed_member_statuses(apps, schema_editor):
    MemberStatus = apps.get_model("members", "MemberStatus")
    Member = apps.get_model("members", "Member")
    defaults = [
        ("active", "Active", 0),
        ("resign", "Resign", 1),
        ("suspended", "Suspended", 2),
        ("deceased", "Deceased", 3),
        ("inactive", "Inactive", 4),
    ]
    slug_to_obj = {}
    for slug, name, sort_order in defaults:
        obj, _ = MemberStatus.objects.get_or_create(
            slug=slug,
            defaults={"name": name, "sort_order": sort_order, "is_active": True},
        )
        slug_to_obj[slug] = obj

    # Map free-text membership_status labels onto the catalog where possible.
    label_map = {s.name.lower(): s for s in slug_to_obj.values()}
    label_map.update({s.slug: s for s in slug_to_obj.values()})
    active = slug_to_obj["active"]
    for m in Member.objects.all().iterator():
        raw = (m.membership_status or "").strip().lower()
        status = label_map.get(raw) or (active if m.is_active else slug_to_obj["inactive"])
        Member.objects.filter(pk=m.pk).update(
            member_status_id=status.pk,
            membership_status=status.name,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0027_member_complete_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to hide this status from new assignments.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member status",
                "verbose_name_plural": "Member statuses",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AlterField(
            model_name="member",
            name="membership_status",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Display label kept in sync with member status when set.",
                max_length=100,
                verbose_name="Status (label)",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="member_status",
            field=models.ForeignKey(
                blank=True,
                help_text="Membership lifecycle status (e.g. Active, Resign).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="members",
                to="members.memberstatus",
                verbose_name="Status",
            ),
        ),
        migrations.RunPython(seed_member_statuses, noop_reverse),
    ]
