from decimal import Decimal
from django.core.management.base import BaseCommand
from inventory.models import Category, Product

PRODUCTS = [
    # (category_name, barcode, product_name, price)
    # 1. Electronics
    ("Electronics", "ELEC001", "VoltSync Wireless Earbuds", Decimal("1200.00")),
    ("Electronics", "ELEC002", "ApexView 4K Smart TV (50\")", Decimal("28000.00")),
    ("Electronics", "ELEC003", "ChargeFusion 20W Power Bank", Decimal("800.00")),
    ("Electronics", "ELEC004", "NanoDrive 1TB SSD", Decimal("4500.00")),
    ("Electronics", "ELEC005", "GlidePro Optical Mouse", Decimal("350.00")),
    ("Electronics", "ELEC006", "EchoCast Smart Speaker", Decimal("2000.00")),
    ("Electronics", "ELEC007", "FlexiPort USB-C Hub", Decimal("1100.00")),
    ("Electronics", "ELEC008", "StealthSound Noise-Cancelling Headphones", Decimal("3200.00")),
    ("Electronics", "ELEC009", "QuickTemp Digital Thermometer", Decimal("250.00")),
    ("Electronics", "ELEC010", "VoltHub Surge Protector", Decimal("600.00")),
    ("Electronics", "ELEC011", "VisionX Webcam with Ring Light", Decimal("1500.00")),
    ("Electronics", "ELEC012", "RapidCharge Wireless Pad", Decimal("900.00")),
    ("Electronics", "ELEC013", "HomeMate Smart Plug", Decimal("550.00")),
    ("Electronics", "ELEC014", "DataKeeper 64GB Flash Drive", Decimal("300.00")),
    ("Electronics", "ELEC015", "SoundVibe Bluetooth Speaker", Decimal("1800.00")),
    ("Electronics", "ELEC016", "GameMaster Mechanical Keyboard", Decimal("2500.00")),
    ("Electronics", "ELEC017", "NightOwl Security Camera", Decimal("1700.00")),
    ("Electronics", "ELEC018", "FlexiCharge Multi-Device Charger", Decimal("1000.00")),
    ("Electronics", "ELEC019", "PixelPerfect Monitor Stand", Decimal("1300.00")),
    ("Electronics", "ELEC020", "CryoFan Personal Air Cooler", Decimal("950.00")),

    # 2. Clothing & Apparel
    ("Clothing & Apparel", "CLTH001", "BreezeTec Summer Polo", Decimal("450.00")),
    ("Clothing & Apparel", "CLTH002", "CozyKnit Hoodie", Decimal("800.00")),
    ("Clothing & Apparel", "CLTH003", "FlexMove Jogger Pants", Decimal("600.00")),
    ("Clothing & Apparel", "CLTH004", "SilkWeave Sleep Shirt", Decimal("350.00")),
    ("Clothing & Apparel", "CLTH005", "UrbanShell Windbreaker Jacket", Decimal("1200.00")),
    ("Clothing & Apparel", "CLTH006", "SoftTee Crewneck (6-pack)", Decimal("900.00")),
    ("Clothing & Apparel", "CLTH007", "NightDown Puffer Vest", Decimal("1500.00")),
    ("Clothing & Apparel", "CLTH008", "AllDayFit Compression Leggings", Decimal("550.00")),
    ("Clothing & Apparel", "CLTH009", "ClassicHerring Suit Blazer", Decimal("3000.00")),
    ("Clothing & Apparel", "CLTH010", "LinenBreeze Beach Shirt", Decimal("400.00")),
    ("Clothing & Apparel", "CLTH011", "ThermaWool Base Layer", Decimal("700.00")),
    ("Clothing & Apparel", "CLTH012", "DenimFusion Stretch Jeans", Decimal("1000.00")),
    ("Clothing & Apparel", "CLTH013", "RainGuard Trench Coat", Decimal("1800.00")),
    ("Clothing & Apparel", "CLTH014", "YogaWrap Cardigan", Decimal("650.00")),
    ("Clothing & Apparel", "CLTH015", "TrailBlaze Hiking Shirt", Decimal("500.00")),
    ("Clothing & Apparel", "CLTH016", "SeamlessSport Tank Top", Decimal("300.00")),
    ("Clothing & Apparel", "CLTH017", "CottonCloud Boxer Briefs (4-pack)", Decimal("450.00")),
    ("Clothing & Apparel", "CLTH018", "EveningSilk Blouse", Decimal("850.00")),
    ("Clothing & Apparel", "CLTH019", "KidProof School Uniform Pants", Decimal("550.00")),
    ("Clothing & Apparel", "CLTH020", "ReflectiveRun Night Jacket", Decimal("1100.00")),

    # 3. Home & Kitchen
    ("Home & Kitchen", "HOMK001", "SpinPro Non-Stick Fry Pan", Decimal("600.00")),
    ("Home & Kitchen", "HOMK002", "HydroPeak Glass Kettle", Decimal("750.00")),
    ("Home & Kitchen", "HOMK003", "SmartScoop Rice Cooker (1.8L)", Decimal("1200.00")),
    ("Home & Kitchen", "HOMK004", "BladeMaster Chef Knife Set", Decimal("1500.00")),
    ("Home & Kitchen", "HOMK005", "DustShield Vacuum Sealer", Decimal("2000.00")),
    ("Home & Kitchen", "HOMK006", "AromaBrew Pour-Over Coffee Maker", Decimal("450.00")),
    ("Home & Kitchen", "HOMK007", "StackLock Food Storage Containers (12-pack)", Decimal("800.00")),
    ("Home & Kitchen", "HOMK008", "SilentChop Mini Chopper", Decimal("900.00")),
    ("Home & Kitchen", "HOMK009", "LintFree Microfiber Towels (8-pack)", Decimal("400.00")),
    ("Home & Kitchen", "HOMK010", "GlideSteam Iron", Decimal("1100.00")),
    ("Home & Kitchen", "HOMK011", "SpiceVault Carousel Organizer", Decimal("500.00")),
    ("Home & Kitchen", "HOMK012", "EasyPress Sandwich Maker", Decimal("700.00")),
    ("Home & Kitchen", "HOMK013", "ShelfGenie Under-Sink Mat", Decimal("300.00")),
    ("Home & Kitchen", "HOMK014", "OilMist Sprayer Bottle", Decimal("200.00")),
    ("Home & Kitchen", "HOMK015", "DrainSnake Hair Catcher", Decimal("150.00")),
    ("Home & Kitchen", "HOMK016", "PeelMagic Vegetable Peeler", Decimal("120.00")),
    ("Home & Kitchen", "HOMK017", "HeatHold Oven Mitts (2-pack)", Decimal("350.00")),
    ("Home & Kitchen", "HOMK018", "BriteView LED Under-Cabinet Light", Decimal("450.00")),
    ("Home & Kitchen", "HOMK019", "CrushIce Manual Blender", Decimal("600.00")),
    ("Home & Kitchen", "HOMK020", "ZeroDrip Wine Pourer", Decimal("180.00")),

    # 4. Beauty & Personal Care
    ("Beauty & Personal Care", "BEAU001", "GlowDew Vitamin C Serum", Decimal("450.00")),
    ("Beauty & Personal Care", "BEAU002", "SilkTouch Hair Removal Cream", Decimal("200.00")),
    ("Beauty & Personal Care", "BEAU003", "AquaFresh Charcoal Face Wash", Decimal("180.00")),
    ("Beauty & Personal Care", "BEAU004", "LashLift Volumizing Mascara", Decimal("250.00")),
    ("Beauty & Personal Care", "BEAU005", "SmoothBalm Lip Scrub", Decimal("150.00")),
    ("Beauty & Personal Care", "BEAU006", "CleanPore Nose Strips (10-pack)", Decimal("200.00")),
    ("Beauty & Personal Care", "BEAU007", "RadianceShield Sunscreen SPF 50", Decimal("350.00")),
    ("Beauty & Personal Care", "BEAU008", "HydraPlump Overnight Mask", Decimal("400.00")),
    ("Beauty & Personal Care", "BEAU009", "BrowDefine Micro Pencil", Decimal("180.00")),
    ("Beauty & Personal Care", "BEAU010", "SoftTouch Bamboo Cotton Pads (50-pack)", Decimal("250.00")),
    ("Beauty & Personal Care", "BEAU011", "ManeStrong Biotin Shampoo", Decimal("300.00")),
    ("Beauty & Personal Care", "BEAU012", "VelvetMatte Lipstick Set (5 shades)", Decimal("600.00")),
    ("Beauty & Personal Care", "BEAU013", "BodySmooth Coffee Scrub", Decimal("280.00")),
    ("Beauty & Personal Care", "BEAU014", "NailPro Glass File Set", Decimal("180.00")),
    ("Beauty & Personal Care", "BEAU015", "PureMist Facial Toner Spray", Decimal("220.00")),
    ("Beauty & Personal Care", "BEAU016", "AgeLock Retinol Night Cream", Decimal("500.00")),
    ("Beauty & Personal Care", "BEAU017", "ScalpSoothe Tea Tree Oil", Decimal("350.00")),
    ("Beauty & Personal Care", "BEAU018", "BlotPerfect Oil Control Sheets (100 ct)", Decimal("150.00")),
    ("Beauty & Personal Care", "BEAU019", "FootSilk Cracked Heel Balm", Decimal("200.00")),
    ("Beauty & Personal Care", "BEAU020", "MistAway Deodorant Wipes (30 ct)", Decimal("180.00")),

    # 5. Health & Wellness
    ("Health & Wellness", "HLTH001", "PostureAlign Back Brace", Decimal("550.00")),
    ("Health & Wellness", "HLTH002", "SleepDeep Melatonin Gummies (60 ct)", Decimal("450.00")),
    ("Health & Wellness", "HLTH003", "PainEase Heating Pad", Decimal("600.00")),
    ("Health & Wellness", "HLTH004", "StepCare Memory Foam Insoles", Decimal("350.00")),
    ("Health & Wellness", "HLTH005", "HydrateMax Electrolyte Powder (30 servings)", Decimal("400.00")),
    ("Health & Wellness", "HLTH006", "BreathWell Nasal Strips (40 ct)", Decimal("300.00")),
    ("Health & Wellness", "HLTH007", "FlexiWrap Compression Bandage", Decimal("250.00")),
    ("Health & Wellness", "HLTH008", "MindCalm Lavender Aromatherapy Roll-On", Decimal("280.00")),
    ("Health & Wellness", "HLTH009", "CoreFit Ab Wheel", Decimal("500.00")),
    ("Health & Wellness", "HLTH010", "DailyVite Multivitamin (90 tabs)", Decimal("700.00")),
    ("Health & Wellness", "HLTH011", "StressLess Herbal Tea Bags (20 ct)", Decimal("220.00")),
    ("Health & Wellness", "HLTH012", "KneeGuard Patella Strap", Decimal("380.00")),
    ("Health & Wellness", "HLTH013", "WarmStone Massage Roller", Decimal("300.00")),
    ("Health & Wellness", "HLTH014", "SnoozeEZ Weighted Blanket (15 lbs)", Decimal("2500.00")),
    ("Health & Wellness", "HLTH015", "PulseTrack Blood Pressure Monitor", Decimal("1800.00")),
    ("Health & Wellness", "HLTH016", "EarClear Wax Removal Kit", Decimal("250.00")),
    ("Health & Wellness", "HLTH017", "FitStep Digital Pedometer", Decimal("450.00")),
    ("Health & Wellness", "HLTH018", "ChillPulse Ice Pack Wrap", Decimal("320.00")),
    ("Health & Wellness", "HLTH019", "JointGlide Glucosamine Cream", Decimal("500.00")),
    ("Health & Wellness", "HLTH020", "ShieldTouch Disposable Gloves (100 ct)", Decimal("400.00")),

    # 6. Sports & Fitness
    ("Sports & Fitness", "SPRT001", "GripMax Yoga Mat (8mm)", Decimal("800.00")),
    ("Sports & Fitness", "SPRT002", "SpeedLace Running Shoes", Decimal("1500.00")),
    ("Sports & Fitness", "SPRT003", "IronCast Adjustable Dumbbell (50 lbs)", Decimal("3500.00")),
    ("Sports & Fitness", "SPRT004", "SweatDry Workout Towel", Decimal("250.00")),
    ("Sports & Fitness", "SPRT005", "FlexBar Resistance Loop Bands (5 levels)", Decimal("600.00")),
    ("Sports & Fitness", "SPRT006", "TrailGrip Hiking Poles (pair)", Decimal("1200.00")),
    ("Sports & Fitness", "SPRT007", "HydraSip Squeeze Water Bottle (32 oz)", Decimal("350.00")),
    ("Sports & Fitness", "SPRT008", "CoreBalance Exercise Ball", Decimal("700.00")),
    ("Sports & Fitness", "SPRT009", "JumpPro Tangle-Free Skipping Rope", Decimal("200.00")),
    ("Sports & Fitness", "SPRT010", "WristLock Weightlifting Gloves", Decimal("450.00")),
    ("Sports & Fitness", "SPRT011", "StepClimber Mini Stepper", Decimal("1800.00")),
    ("Sports & Fitness", "SPRT012", "FoamRoller Deep Tissue (18\")", Decimal("550.00")),
    ("Sports & Fitness", "SPRT013", "AnkleSafe Neoprene Support Sleeve", Decimal("380.00")),
    ("Sports & Fitness", "SPRT014", "SwimTech Silicone Cap", Decimal("250.00")),
    ("Sports & Fitness", "SPRT015", "PunchMaster Speed Bag", Decimal("1000.00")),
    ("Sports & Fitness", "SPRT016", "TrailBlaze Hydration Vest", Decimal("1400.00")),
    ("Sports & Fitness", "SPRT017", "KneeSleeve Heavy Duty (pair)", Decimal("600.00")),
    ("Sports & Fitness", "SPRT018", "StretchStrap Flexibility Band", Decimal("320.00")),
    ("Sports & Fitness", "SPRT019", "SandBag Heavy Duty (40 lbs)", Decimal("900.00")),
    ("Sports & Fitness", "SPRT020", "SpinFit Cycling Gloves", Decimal("500.00")),

    # 7. Automotive
    ("Automotive", "AUTO001", "DustOff Car Duster", Decimal("350.00")),
    ("Automotive", "AUTO002", "AirFlow Tire Inflator (12V)", Decimal("1200.00")),
    ("Automotive", "AUTO003", "ScratchAway Paint Repair Pen", Decimal("250.00")),
    ("Automotive", "AUTO004", "GripGuard Car Floor Mats (4 pcs)", Decimal("1800.00")),
    ("Automotive", "AUTO005", "ScentWave Vent Clip Air Freshener (3-pack)", Decimal("300.00")),
    ("Automotive", "AUTO006", "LightMate LED Headlight Bulbs (pair)", Decimal("1000.00")),
    ("Automotive", "AUTO007", "TowEco Emergency Rope (20 ft)", Decimal("450.00")),
    ("Automotive", "AUTO008", "DashGuard Sun Shade", Decimal("500.00")),
    ("Automotive", "AUTO009", "CleanView Windshield Washer Tablets (20 ct)", Decimal("280.00")),
    ("Automotive", "AUTO010", "PhoneDrive Magnetic Car Mount", Decimal("350.00")),
    ("Automotive", "AUTO011", "IceScraper Snow Brush Combo", Decimal("400.00")),
    ("Automotive", "AUTO012", "SeatShield Pet Cover", Decimal("1500.00")),
    ("Automotive", "AUTO013", "OilSwift Funnel with Filter", Decimal("200.00")),
    ("Automotive", "AUTO014", "BatteryCheck Digital Tester", Decimal("800.00")),
    ("Automotive", "AUTO015", "TrunkTidy Organizer Bag", Decimal("600.00")),
    ("Automotive", "AUTO016", "VisorMate Glasses Holder", Decimal("180.00")),
    ("Automotive", "AUTO017", "ChipDefense Clear Bra Film (per meter)", Decimal("500.00")),
    ("Automotive", "AUTO018", "KeyGuard Carbon Fiber Case", Decimal("350.00")),
    ("Automotive", "AUTO019", "JumpStart Lithium Booster Pack", Decimal("3000.00")),
    ("Automotive", "AUTO020", "TireTread Depth Gauge", Decimal("250.00")),

    # 8. Toys & Games
    ("Toys & Games", "TOYS001", "BuildBlock 100-Piece Bricks Set", Decimal("600.00")),
    ("Toys & Games", "TOYS002", "RoarStomp Dinosaur Figure", Decimal("350.00")),
    ("Toys & Games", "TOYS003", "SpeedLoop Slot Car Track", Decimal("1200.00")),
    ("Toys & Games", "TOYS004", "PlushPals Unicorn Stuffed Toy (12\")", Decimal("450.00")),
    ("Toys & Games", "TOYS005", "StackRing Silicone Teether", Decimal("200.00")),
    ("Toys & Games", "TOYS006", "BrainFit Puzzle Cube", Decimal("180.00")),
    ("Toys & Games", "TOYS007", "SplashBuddy Floating Bath Toys (6-pack)", Decimal("300.00")),
    ("Toys & Games", "TOYS008", "DrawMaster LCD Writing Tablet", Decimal("550.00")),
    ("Toys & Games", "TOYS009", "ThrowToss Bean Bags (8-pack)", Decimal("400.00")),
    ("Toys & Games", "TOYS010", "FarmNoise Animal Sound Book", Decimal("500.00")),
    ("Toys & Games", "TOYS011", "GlowStars Ceiling Decals (50-pack)", Decimal("250.00")),
    ("Toys & Games", "TOYS012", "MatchMate Memory Card Game", Decimal("220.00")),
    ("Toys & Games", "TOYS013", "SpinWin Bath Spinner Toys", Decimal("280.00")),
    ("Toys & Games", "TOYS014", "BuildRace Wooden Train Set", Decimal("800.00")),
    ("Toys & Games", "TOYS015", "SoapBubbles Giant Wand Kit", Decimal("180.00")),
    ("Toys & Games", "TOYS016", "CodeBot STEM Robot Kit", Decimal("2000.00")),
    ("Toys & Games", "TOYS017", "HammerTap Pounding Bench", Decimal("450.00")),
    ("Toys & Games", "TOYS018", "StringArt Animal Craft Kit", Decimal("300.00")),
    ("Toys & Games", "TOYS019", "MazeMagnet Ball Labyrinth", Decimal("350.00")),
    ("Toys & Games", "TOYS020", "PuzzleLink 3D Brain Teaser", Decimal("280.00")),

    # 9. Books & Stationery
    ("Books & Stationery", "BOOK001", "NoteFlow Spiral Notebook (200 pgs)", Decimal("120.00")),
    ("Books & Stationery", "BOOK002", "InkGlide Gel Pens (12 colors)", Decimal("250.00")),
    ("Books & Stationery", "BOOK003", "StickyTab Page Markers (4 packs)", Decimal("150.00")),
    ("Books & Stationery", "BOOK004", "ErgoGrip Mechanical Pencil (0.7mm)", Decimal("180.00")),
    ("Books & Stationery", "BOOK005", "DeskMate A5 Planner (undated)", Decimal("350.00")),
    ("Books & Stationery", "BOOK006", "HighLume Fluorescent Markers (5-pack)", Decimal("200.00")),
    ("Books & Stationery", "BOOK007", "SealTape Refillable Dispenser", Decimal("120.00")),
    ("Books & Stationery", "BOOK008", "CutPrecise Titanium Scissors", Decimal("250.00")),
    ("Books & Stationery", "BOOK009", "EraseAway Whiteboard Eraser", Decimal("80.00")),
    ("Books & Stationery", "BOOK010", "FileFold Colored Index Cards (100 ct)", Decimal("180.00")),
    ("Books & Stationery", "BOOK011", "BindRing Loose Leaf Binder", Decimal("300.00")),
    ("Books & Stationery", "BOOK012", "NoteGlue Adhesive Roller", Decimal("150.00")),
    ("Books & Stationery", "BOOK013", "StampClear Date Stamper", Decimal("220.00")),
    ("Books & Stationery", "BOOK014", "RulerPro Stainless Steel (12\")", Decimal("100.00")),
    ("Books & Stationery", "BOOK015", "PenLoop Silicone Holder", Decimal("60.00")),
    ("Books & Stationery", "BOOK016", "CornerRound Paper Punch", Decimal("180.00")),
    ("Books & Stationery", "BOOK017", "ErgoDesk Wrist Rest Pad", Decimal("280.00")),
    ("Books & Stationery", "BOOK018", "SharpPoint Pencil Sharpener (auto)", Decimal("200.00")),
    ("Books & Stationery", "BOOK019", "MailSafe Bubble Envelope (10-pack)", Decimal("300.00")),
    ("Books & Stationery", "BOOK020", "TabWrite Divider Tabs (8-tab set)", Decimal("120.00")),

    # 10. Food & Beverages
    ("Food & Beverages", "FOOD001", "RoastMaster Whole Bean Coffee (12 oz)", Decimal("450.00")),
    ("Food & Beverages", "FOOD002", "HoneyDrip Pure Raw Honey (16 oz)", Decimal("550.00")),
    ("Food & Beverages", "FOOD003", "CrunchTime Almonds Sea Salt (10 oz)", Decimal("350.00")),
    ("Food & Beverages", "FOOD004", "SoupBowl Instant Ramen Cup (6-pack)", Decimal("250.00")),
    ("Food & Beverages", "FOOD005", "BerryBlend Dried Fruit Mix (8 oz)", Decimal("300.00")),
    ("Food & Beverages", "FOOD006", "MapleRich Organic Syrup (12.7 oz)", Decimal("600.00")),
    ("Food & Beverages", "FOOD007", "SpiceTrail Taco Seasoning (3 oz)", Decimal("150.00")),
    ("Food & Beverages", "FOOD008", "OatPure Gluten-Free Oats (24 oz)", Decimal("380.00")),
    ("Food & Beverages", "FOOD009", "ChillPop Fruit Popsicles (12 ct)", Decimal("200.00")),
    ("Food & Beverages", "FOOD010", "SaucePot Marinara Pasta Sauce (24 oz)", Decimal("220.00")),
    ("Food & Beverages", "FOOD011", "EnergyBite Granola Bar (12 ct)", Decimal("280.00")),
    ("Food & Beverages", "FOOD012", "TeaLeaf Morning Blend (20 bags)", Decimal("180.00")),
    ("Food & Beverages", "FOOD013", "BrothBase Chicken Stock Cube (30 ct)", Decimal("200.00")),
    ("Food & Beverages", "FOOD014", "OliveDrizzle Extra Virgin Oil (16.9 oz)", Decimal("700.00")),
    ("Food & Beverages", "FOOD015", "RicePerfect Jasmine Rice (5 lbs)", Decimal("350.00")),
    ("Food & Beverages", "FOOD016", "NutCrunch Peanut Butter (16 oz)", Decimal("250.00")),
    ("Food & Beverages", "FOOD017", "CacaoRich Dark Chocolate Bar (85%)", Decimal("180.00")),
    ("Food & Beverages", "FOOD018", "LemonZest Citrus Juice (8 oz)", Decimal("120.00")),
    ("Food & Beverages", "FOOD019", "SaltFlake Pink Himalayan Salt (12 oz)", Decimal("150.00")),
    ("Food & Beverages", "FOOD020", "BeanGround Decaf Coffee (12 oz)", Decimal("420.00")),

    # 11. Furniture
    ("Furniture", "FURN001", "SlimFit Sofa (2-seater)", Decimal("12000.00")),
    ("Furniture", "FURN002", "NightStand Bamboo Drawer", Decimal("1800.00")),
    ("Furniture", "FURN003", "DeskPro Adjustable Height Table", Decimal("8500.00")),
    ("Furniture", "FURN004", "CoilDream Queen Mattress", Decimal("15000.00")),
    ("Furniture", "FURN005", "ShelfCube Modular Storage Unit", Decimal("3500.00")),
    ("Furniture", "FURN006", "RelaxSwivel Recliner Chair", Decimal("7000.00")),
    ("Furniture", "FURN007", "FoldMate Dining Table (extends)", Decimal("9000.00")),
    ("Furniture", "FURN008", "Leggero Floating Nightstand", Decimal("1200.00")),
    ("Furniture", "FURN009", "StackBin Plastic Drawer Organizer", Decimal("800.00")),
    ("Furniture", "FURN010", "LaptopLap Bed Tray", Decimal("500.00")),
    ("Furniture", "FURN011", "SpaceWise Under-Bed Storage Box", Decimal("600.00")),
    ("Furniture", "FURN012", "ArmRest Folding Chair (set of 4)", Decimal("2500.00")),
    ("Furniture", "FURN013", "CornerFit Bookshelf (5-tier)", Decimal("3000.00")),
    ("Furniture", "FURN014", "PetStep Ramp for Furniture", Decimal("2200.00")),
    ("Furniture", "FURN015", "ShoeCabin 12-Pair Entryway Rack", Decimal("1500.00")),
    ("Furniture", "FURN016", "MediaGlide TV Stand (fits 65\")", Decimal("5500.00")),
    ("Furniture", "FURN017", "DropLeaf Wall-Mounted Desk", Decimal("2800.00")),
    ("Furniture", "FURN018", "LoungePillow Floor Chair", Decimal("1000.00")),
    ("Furniture", "FURN019", "FabricCube Storage Bins (6-pack)", Decimal("900.00")),
    ("Furniture", "FURN020", "RotateStool Kitchen Step Stool", Decimal("1100.00")),

    # 12. Office Supplies
    ("Office Supplies", "OFFC001", "StackTray Mesh Letter Tray (3-tier)", Decimal("450.00")),
    ("Office Supplies", "OFFC002", "ClipForce Binder Clips (24-pack)", Decimal("120.00")),
    ("Office Supplies", "OFFC003", "StapleEco Half Strip Stapler", Decimal("250.00")),
    ("Office Supplies", "OFFC004", "TapeRunner Retractable Dispenser", Decimal("180.00")),
    ("Office Supplies", "OFFC005", "PenCup Bamboo Desk Organizer", Decimal("300.00")),
    ("Office Supplies", "OFFC006", "FileSorter Expanding Wallet (13 pockets)", Decimal("280.00")),
    ("Office Supplies", "OFFC007", "LabelWrite Clear Address Labels (50 ct)", Decimal("200.00")),
    ("Office Supplies", "OFFC008", "PunchAlign 3-Hole Punch", Decimal("350.00")),
    ("Office Supplies", "OFFC009", "EraseBoard Whiteboard (12\"x16\")", Decimal("600.00")),
    ("Office Supplies", "OFFC010", "PushPin Glass Head Pins (50 ct)", Decimal("150.00")),
    ("Office Supplies", "OFFC011", "BandRoll Rubber Bands (1 lb)", Decimal("250.00")),
    ("Office Supplies", "OFFC012", "StickyNote Canary Yellow (12 pads)", Decimal("180.00")),
    ("Office Supplies", "OFFC013", "CashBox Locking Money Drawer", Decimal("1200.00")),
    ("Office Supplies", "OFFC014", "NamePlate Acrylic Desk Sign", Decimal("250.00")),
    ("Office Supplies", "OFFC015", "FolderTab Manila Folders (25 ct)", Decimal("150.00")),
    ("Office Supplies", "OFFC016", "SheetGuard Page Protectors (50 ct)", Decimal("220.00")),
    ("Office Supplies", "OFFC017", "InkRefill Black Printer Cartridge", Decimal("800.00")),
    ("Office Supplies", "OFFC018", "MarkerDry Fine Tip (4 colors)", Decimal("300.00")),
    ("Office Supplies", "OFFC019", "TimeClock Punch Card Rack", Decimal("500.00")),
    ("Office Supplies", "OFFC020", "EnvelopeSeal Moistener Pen", Decimal("100.00")),

    # 13. Pet Supplies
    ("Pet Supplies", "PETS001", "ChewGuard Rope Toy (large)", Decimal("250.00")),
    ("Pet Supplies", "PETS002", "CozyCave Dog Bed (machine washable)", Decimal("1200.00")),
    ("Pet Supplies", "PETS003", "LeashFlex Reflective Nylon (6 ft)", Decimal("300.00")),
    ("Pet Supplies", "PETS004", "FreshBowl No-Spill Water Bowl", Decimal("350.00")),
    ("Pet Supplies", "PETS005", "PawClean Mud Remover Cup", Decimal("280.00")),
    ("Pet Supplies", "PETS006", "CrunchBite Dental Bone (3-pack)", Decimal("400.00")),
    ("Pet Supplies", "PETS007", "HarnessSafe No-Pull Vest (adjustable)", Decimal("550.00")),
    ("Pet Supplies", "PETS008", "KittyLitter Clumping Grass (10 lbs)", Decimal("450.00")),
    ("Pet Supplies", "PETS009", "FlakeFuel Fish Food (2.5 oz)", Decimal("180.00")),
    ("Pet Supplies", "PETS010", "BrushEasy Shedding Comb", Decimal("200.00")),
    ("Pet Supplies", "PETS011", "PoopBag Eco-Friendly Rolls (120 ct)", Decimal("250.00")),
    ("Pet Supplies", "PETS012", "IDTag Stainless Steel Engraved", Decimal("150.00")),
    ("Pet Supplies", "PETS013", "CageFresh Small Animal Bedding (20L)", Decimal("300.00")),
    ("Pet Supplies", "PETS014", "ScratchPad Cat Cardboard Lounge", Decimal("400.00")),
    ("Pet Supplies", "PETS015", "HamsterHideout Tunnel Set", Decimal("280.00")),
    ("Pet Supplies", "PETS016", "TreatBall Interactive Feeder", Decimal("350.00")),
    ("Pet Supplies", "PETS017", "FleaStop Collar (8-month)", Decimal("500.00")),
    ("Pet Supplies", "PETS018", "PetStep Car Ramp", Decimal("1800.00")),
    ("Pet Supplies", "PETS019", "BirdSwing Wooden Perch Toy", Decimal("320.00")),
    ("Pet Supplies", "PETS020", "TravelCrate Foldable Carrier (small)", Decimal("900.00")),

    # 14. Baby Products
    ("Baby Products", "BABY001", "SleepSack Wearable Blanket (0-6m)", Decimal("700.00")),
    ("Baby Products", "BABY002", "WipeWarm Portable Warmer", Decimal("1200.00")),
    ("Baby Products", "BABY003", "SipSafe Silicone Sippy Cup (8 oz)", Decimal("350.00")),
    ("Baby Products", "BABY004", "SoothPacifier BPA-Free (2-pack)", Decimal("250.00")),
    ("Baby Products", "BABY005", "RockNest Automatic Bouncer", Decimal("3500.00")),
    ("Baby Products", "BABY006", "BurpCloth Bamboo (6-pack)", Decimal("400.00")),
    ("Baby Products", "BABY007", "NailSnail Safety Trimmer", Decimal("280.00")),
    ("Baby Products", "BABY008", "BathFloat Non-Slip Tub Support", Decimal("550.00")),
    ("Baby Products", "BABY009", "TeetheRing Cooling Gel Toy", Decimal("300.00")),
    ("Baby Products", "BABY010", "StrollClip Stroller Organizer", Decimal("450.00")),
    ("Baby Products", "BABY011", "ChangeMat Waterproof Pad (2-pack)", Decimal("500.00")),
    ("Baby Products", "BABY012", "BibEasy Roll-Up Silicone Bib", Decimal("250.00")),
    ("Baby Products", "BABY013", "SoundDream White Noise Machine", Decimal("1500.00")),
    ("Baby Products", "BABY014", "BottleWarm Rapid Heater", Decimal("800.00")),
    ("Baby Products", "BABY015", "CrawlKnee Baby Pads", Decimal("350.00")),
    ("Baby Products", "BABY016", "FoodPress Baby Food Masher", Decimal("200.00")),
    ("Baby Products", "BABY017", "DiaperBackpack Spill-Proof Bag", Decimal("1100.00")),
    ("Baby Products", "BABY018", "NestCam Digital Baby Monitor", Decimal("4000.00")),
    ("Baby Products", "BABY019", "SwaddleWrap Adjustable Velcro", Decimal("400.00")),
    ("Baby Products", "BABY020", "PottyStep Toilet Trainer Seat", Decimal("600.00")),

    # 15. Garden & Outdoor
    ("Garden & Outdoor", "GRDN001", "DigMaster Trowel Set (3 pcs)", Decimal("300.00")),
    ("Garden & Outdoor", "GRDN002", "GrowBag Fabric Pot (5 gallon)", Decimal("150.00")),
    ("Garden & Outdoor", "GRDN003", "WeedOut Long-Handle Hoe", Decimal("400.00")),
    ("Garden & Outdoor", "GRDN004", "PruneSharp Bypass Shears", Decimal("350.00")),
    ("Garden & Outdoor", "GRDN005", "WaterFlow Soaker Hose (50 ft)", Decimal("800.00")),
    ("Garden & Outdoor", "GRDN006", "SeedStart 72-Cell Tray", Decimal("250.00")),
    ("Garden & Outdoor", "GRDN007", "GlowWalk Solar Path Lights (6-pack)", Decimal("1200.00")),
    ("Garden & Outdoor", "GRDN008", "BugOff Citronella Candle (14 oz)", Decimal("280.00")),
    ("Garden & Outdoor", "GRDN009", "LeafScoop Garden Gloves (pair)", Decimal("200.00")),
    ("Garden & Outdoor", "GRDN010", "CompostBin Tumbling Mixer (40 gal)", Decimal("5000.00")),
    ("Garden & Outdoor", "GRDN011", "SprayGuard Hose Nozzle", Decimal("250.00")),
    ("Garden & Outdoor", "GRDN012", "BarkMulch Cedar Chips (2 cu ft)", Decimal("350.00")),
    ("Garden & Outdoor", "GRDN013", "PlantTag Waterproof Markers (30 ct)", Decimal("180.00")),
    ("Garden & Outdoor", "GRDN014", "TrellisNet Climbing Plant Support", Decimal("300.00")),
    ("Garden & Outdoor", "GRDN015", "SoilTest pH & Moisture Meter", Decimal("450.00")),
    ("Garden & Outdoor", "GRDN016", "RainGauge Decorative Glass", Decimal("400.00")),
    ("Garden & Outdoor", "GRDN017", "PotLifter Heavy Duty Carrier", Decimal("500.00")),
    ("Garden & Outdoor", "GRDN018", "MossKill Roof Powder (5 lbs)", Decimal("600.00")),
    ("Garden & Outdoor", "GRDN019", "BirdFeeder Hanging Metal", Decimal("550.00")),
    ("Garden & Outdoor", "GRDN020", "FencePost Ground Anchor", Decimal("350.00")),

    # 16. Tools & Hardware
    ("Tools & Hardware", "TOOL001", "GripClamp Quick-Release (12\")", Decimal("450.00")),
    ("Tools & Hardware", "TOOL002", "HammerSteel 16oz Curved Claw", Decimal("500.00")),
    ("Tools & Hardware", "TOOL003", "ScrewMaster 50-Piece Bit Set", Decimal("600.00")),
    ("Tools & Hardware", "TOOL004", "TapeRule Magnetic Lock (25 ft)", Decimal("350.00")),
    ("Tools & Hardware", "TOOL005", "LevelPro Torpedo Level (9\")", Decimal("280.00")),
    ("Tools & Hardware", "TOOL006", "PliersGrip Groove Joint (10\")", Decimal("400.00")),
    ("Tools & Hardware", "TOOL007", "HexKey Ball End Set (13 pcs)", Decimal("300.00")),
    ("Tools & Hardware", "TOOL008", "UtilityKnife Snap-Off Blade", Decimal("180.00")),
    ("Tools & Hardware", "TOOL009", "StudFinder Wall Scanner", Decimal("800.00")),
    ("Tools & Hardware", "TOOL010", "SocketSet Ratchet Drive (72-tooth)", Decimal("1500.00")),
    ("Tools & Hardware", "TOOL011", "WrenchAdjustable Chrome (8\")", Decimal("350.00")),
    ("Tools & Hardware", "TOOL012", "SawHand Mini Hacksaw", Decimal("250.00")),
    ("Tools & Hardware", "TOOL013", "DrillBit Titanium Set (15 pcs)", Decimal("700.00")),
    ("Tools & Hardware", "TOOL014", "FlashLight LED Rechargeable", Decimal("450.00")),
    ("Tools & Hardware", "TOOL015", "ViseGrip Locking Pliers (7\")", Decimal("500.00")),
    ("Tools & Hardware", "TOOL016", "ToolBox Heavy Duty Cantilever", Decimal("2000.00")),
    ("Tools & Hardware", "TOOL017", "WireStripper Self-Adjusting", Decimal("300.00")),
    ("Tools & Hardware", "TOOL018", "GlueGun Mini High Temp", Decimal("350.00")),
    ("Tools & Hardware", "TOOL019", "SandBlock 120/240 Grit (6-pack)", Decimal("250.00")),
    ("Tools & Hardware", "TOOL020", "LaserCross Line Level", Decimal("1000.00")),

    # 17. Mobile Accessories
    ("Mobile Accessories", "MOBL001", "ArmorCase Shockproof Phone Cover", Decimal("300.00")),
    ("Mobile Accessories", "MOBL002", "GlassGuard Tempered Screen Protector (2-pack)", Decimal("250.00")),
    ("Mobile Accessories", "MOBL003", "PowerStick 5000mAh Mini Charger", Decimal("600.00")),
    ("Mobile Accessories", "MOBL004", "CableFlex Braided USB-C (6 ft)", Decimal("200.00")),
    ("Mobile Accessories", "MOBL005", "RingHold Finger Kickstand", Decimal("120.00")),
    ("Mobile Accessories", "MOBL006", "LensKit Phone Camera Set (3 lenses)", Decimal("800.00")),
    ("Mobile Accessories", "MOBL007", "CarBreeze Magnetic Vent Mount", Decimal("350.00")),
    ("Mobile Accessories", "MOBL008", "PortClean Dust Plug Set (10-pack)", Decimal("100.00")),
    ("Mobile Accessories", "MOBL009", "PouchBag Velvet Phone Sleeve", Decimal("180.00")),
    ("Mobile Accessories", "MOBL010", "GameTrigger L/R Buttons", Decimal("250.00")),
    ("Mobile Accessories", "MOBL011", "ChargePad Wireless Charging Stand", Decimal("550.00")),
    ("Mobile Accessories", "MOBL012", "CableKeeper Silicone Tie (8-pack)", Decimal("150.00")),
    ("Mobile Accessories", "MOBL013", "PrivacyShield Matte Screen Film", Decimal("280.00")),
    ("Mobile Accessories", "MOBL014", "NeckBand Phone Lanyard", Decimal("200.00")),
    ("Mobile Accessories", "MOBL015", "PhotoLens Clip-on Selfie Light", Decimal("350.00")),
    ("Mobile Accessories", "MOBL016", "GripRing Metal Phone Holder", Decimal("150.00")),
    ("Mobile Accessories", "MOBL017", "AudioSplit 3.5mm Adapter", Decimal("120.00")),
    ("Mobile Accessories", "MOBL018", "NanoClean UV Phone Sanitizer", Decimal("1200.00")),
    ("Mobile Accessories", "MOBL019", "StandFold Desktop Phone Stand", Decimal("250.00")),
    ("Mobile Accessories", "MOBL020", "BatteryCase 10000mAh Charging Case", Decimal("1500.00")),

    # 18. Footwear
    ("Footwear", "FOOT001", "CloudStep Running Shoes (Men's)", Decimal("1800.00")),
    ("Footwear", "FOOT002", "FlexWalk Slip-On Sneakers (Women's)", Decimal("1500.00")),
    ("Footwear", "FOOT003", "TrailGrip Hiking Boots (waterproof)", Decimal("3000.00")),
    ("Footwear", "FOOT004", "HomeSoft Memory Foam Slippers", Decimal("350.00")),
    ("Footwear", "FOOT005", "OfficeComfort Loafers (leather)", Decimal("1200.00")),
    ("Footwear", "FOOT006", "SportSlide Adjustable Sandals", Decimal("500.00")),
    ("Footwear", "FOOT007", "RainGuard Ankle Boots", Decimal("1000.00")),
    ("Footwear", "FOOT008", "GymLift Training Shoes (unisex)", Decimal("1600.00")),
    ("Footwear", "FOOT009", "BeachDry Quick-Dry Water Shoes", Decimal("450.00")),
    ("Footwear", "FOOT010", "CozySock Non-Slip Booties (indoor)", Decimal("250.00")),
    ("Footwear", "FOOT011", "DressLace Oxfords (formal)", Decimal("2200.00")),
    ("Footwear", "FOOT012", "KidProof Velcro Sneakers (toddler)", Decimal("800.00")),
    ("Footwear", "FOOT013", "ZeroDrop Barefoot Shoes", Decimal("1400.00")),
    ("Footwear", "FOOT014", "WinterShield Insulated Boots (-20C)", Decimal("3500.00")),
    ("Footwear", "FOOT015", "CourtGrip Volleyball Shoes", Decimal("1700.00")),
    ("Footwear", "FOOT016", "NightRun Reflective Sneakers", Decimal("1900.00")),
    ("Footwear", "FOOT017", "OrthoStep Arch Support Sandals", Decimal("1000.00")),
    ("Footwear", "FOOT018", "SoftMoc Suede Loafers", Decimal("1300.00")),
    ("Footwear", "FOOT019", "TrekPole Climbing Approach Shoes", Decimal("2500.00")),
    ("Footwear", "FOOT020", "SlideEasy Shoe Horn (metal)", Decimal("150.00")),

    # 19. Jewelry & Accessories
    ("Jewelry & Accessories", "JEWL001", "SilverTide Chain Necklace (18\")", Decimal("800.00")),
    ("Jewelry & Accessories", "JEWL002", "PearlDrops Stud Earrings (set of 3)", Decimal("600.00")),
    ("Jewelry & Accessories", "JEWL003", "LeatherLoop Braided Bracelet", Decimal("350.00")),
    ("Jewelry & Accessories", "JEWL004", "SunRay Gold-Plated Ring", Decimal("500.00")),
    ("Jewelry & Accessories", "JEWL005", "TickTock Minimalist Watch", Decimal("1200.00")),
    ("Jewelry & Accessories", "JEWL006", "GemStone Crystal Pendant", Decimal("700.00")),
    ("Jewelry & Accessories", "JEWL007", "HairPin Set Pearl (6-pack)", Decimal("250.00")),
    ("Jewelry & Accessories", "JEWL008", "BeltStrap Reversible Leather (1.5\")", Decimal("450.00")),
    ("Jewelry & Accessories", "JEWL009", "Sunglare Polarized Aviators", Decimal("900.00")),
    ("Jewelry & Accessories", "JEWL010", "CuffBold Stainless Steel Bracelet", Decimal("400.00")),
    ("Jewelry & Accessories", "JEWL011", "AnkleChain Fine Silver (adjustable)", Decimal("350.00")),
    ("Jewelry & Accessories", "JEWL012", "BroochPin Floral Enamel", Decimal("300.00")),
    ("Jewelry & Accessories", "JEWL013", "TieBar Silver Geometric", Decimal("250.00")),
    ("Jewelry & Accessories", "JEWL014", "NailRing Adjustable Open Band", Decimal("180.00")),
    ("Jewelry & Accessories", "JEWL015", "EarCuff Non-Piercing Set (2 sizes)", Decimal("220.00")),
    ("Jewelry & Accessories", "JEWL016", "LocketHeart Photo Frame Pendant", Decimal("600.00")),
    ("Jewelry & Accessories", "JEWL017", "Wristlet Stretch Beaded (natural stone)", Decimal("280.00")),
    ("Jewelry & Accessories", "JEWL018", "HatClip Magnetic Holder", Decimal("150.00")),
    ("Jewelry & Accessories", "JEWL019", "ScarfRing Silk Slide", Decimal("200.00")),
    ("Jewelry & Accessories", "JEWL020", "LapelPin Mini Initial (gold)", Decimal("180.00")),

    # 20. Grocery Items
    ("Grocery Items", "GROC001", "FarmFresh Whole Milk (1 gallon)", Decimal("380.00")),
    ("Grocery Items", "GROC002", "GoldenGrain Wheat Bread (20 oz)", Decimal("120.00")),
    ("Grocery Items", "GROC003", "CageFree Large Eggs (12 ct)", Decimal("150.00")),
    ("Grocery Items", "GROC004", "GreenLeaf Romaine Lettuce (1 head)", Decimal("80.00")),
    ("Grocery Items", "GROC005", "SweetRipe Bananas (bunch ~3 lbs)", Decimal("120.00")),
    ("Grocery Items", "GROC006", "RedBurst Tomatoes (vine-ripened, 1 lb)", Decimal("70.00")),
    ("Grocery Items", "GROC007", "ProteinPack Chicken Breast (1 lb)", Decimal("180.00")),
    ("Grocery Items", "GROC008", "ButterStick Unsalted (4 ct)", Decimal("200.00")),
    ("Grocery Items", "GROC009", "YogurtCup Mixed Berry (6 oz)", Decimal("50.00")),
    ("Grocery Items", "GROC010", "PastaQuick Elbow Macaroni (16 oz)", Decimal("60.00")),
    ("Grocery Items", "GROC011", "RiceFluff White Rice (2 lbs)", Decimal("90.00")),
    ("Grocery Items", "GROC012", "CannedCorn Sweet Kernel (15 oz)", Decimal("45.00")),
    ("Grocery Items", "GROC013", "SoupBase Tomato Condensed (10.75 oz)", Decimal("40.00")),
    ("Grocery Items", "GROC014", "SnackChip Classic Potato (8 oz)", Decimal("80.00")),
    ("Grocery Items", "GROC015", "FreezePeas Green Peas (16 oz)", Decimal("100.00")),
    ("Grocery Items", "GROC016", "CheeseSlice American Singles (12 ct)", Decimal("180.00")),
    ("Grocery Items", "GROC017", "SauceRed Pizza Sauce (14 oz)", Decimal("70.00")),
    ("Grocery Items", "GROC018", "HoneyOat Cereal (18 oz box)", Decimal("220.00")),
    ("Grocery Items", "GROC019", "WaterPure Spring Water (24-pack 16.9 oz)", Decimal("250.00")),
    ("Grocery Items", "GROC020", "BakeMix Pancake & Waffle (32 oz)", Decimal("150.00")),
]


class Command(BaseCommand):
    help = "Seed the database with 400 products across 20 categories"

    def handle(self, *args, **options):
        created_count = 0
        skipped_count = 0

        # Pre-fetch all categories into a dict for performance
        category_map = {cat.name: cat for cat in Category.objects.all()}

        for category_name, barcode, name, price in PRODUCTS:
            category = category_map.get(category_name)
            if category is None:
                self.stdout.write(
                    self.style.WARNING(
                        f"  Category not found, skipping: {category_name} -> {name}"
                    )
                )
                skipped_count += 1
                continue

            cost = (price * Decimal("0.70")).quantize(Decimal("0.01"))

            obj, created = Product.objects.get_or_create(
                barcode=barcode,
                defaults={
                    "name": name,
                    "category": category,
                    "price": price,
                    "cost": cost,
                    "stock_quantity": 50,
                    "low_stock_threshold": 10,
                    "is_active": True,
                },
            )

            if created:
                created_count += 1
                self.stdout.write(self.style.SUCCESS(f"  Created: [{category_name}] {name} - PHP {price}"))
            else:
                skipped_count += 1
                self.stdout.write(self.style.WARNING(f"  Skipped (exists): {name}"))

        self.stdout.write(
            self.style.SUCCESS(
                f"\nDone. {created_count} products created, {skipped_count} skipped."
            )
        )
